kubernetes-sigs/bootkube

cmd/bootkube/render.go
pkg/asset/asset.go
pkg/asset/k8s.go
pkg/asset/templates/kube-apiserver.yaml
pkg/asset/templates/kube-proxy.yaml
pkg/asset/templates/kubelet.yaml
pkg/asset/tls.go

This patch adds a few flags to configure the generated assets. We may
want to eventually move to something like configMaps or something in the
future, but for now this gets us enough configuration.

cmd/bootkube: Allow config of generated manifests

---

pkg/asset/templates/kube-proxy.yaml

The kube-proxy daemonset should not be limited to master nodes.

assets: remove nodeSelector on kube-proxy

---

pkg/bootkube/bootkube.go

We have all the keys to generate service accounts, but we're not
enabling the plugin.

pkg/bootkube: Add admission-control=ServiceAccount flag

---

README.md

Is there a reason for the added complexity of telling someone to clone into their GOPATH vs go getting? Seems like a left over from when this was a private repo.

README: just use go get

---

hack/multi-node/README.md
hack/single-node/README.md

This patch simply updates the READMEs in the hack directories, now that
the self-killing bootkube code is merged, we no longer should instruct
folks to manually kill the process.

hack: Update READMEs regarding auto-shutdown

---

hack/multi-node/Vagrantfile
hack/multi-node/user-data.sample
hack/single-node/user-data.sample
pkg/asset/templates/kube-apiserver.yaml
pkg/asset/templates/kube-controller-manager.yaml
pkg/asset/templates/kube-proxy.yaml
pkg/asset/templates/kube-scheduler.yaml
pkg/asset/templates/kubelet.yaml

This includes a patched hyperkube built from https://github.com/aaronlevy/kubernetes/commits/v1.2.2_runonce.0 which contains a minor fix so that the downward api exposes the podIP when hostnetwork=true.
Upstream issue: https://github.com/kubernetes/kubernetes/issues/24576

Api endpoint fix

---

hack/multi-node/user-data.sample
hack/single-node/user-data.sample
pkg/asset/templates/kubelet.yaml

This change removes the reliance on the node hostname, which was picked up by the kubelet as the default routeable kubelet hostname. The idea is that it is better to explicitly assign a hostname by flag than to have a dependency on the host node's hostname configuration.
I've tested this against the network booted libvirt VM cluster in [coreos-baremetal #170](https://github.com/coreos/coreos-baremetal/pull/170). I haven't validated with the bootkube Vagrantfiles since I don't have a VirtualBox/VMWare setup.

pkg/asset/templates: Use podIP in kubelet hostname-override

---

pkg/asset/templates/kube-apiserver.yaml
pkg/asset/templates/kube-controller-manager.yaml
pkg/asset/templates/kube-proxy.yaml
pkg/asset/templates/kube-scheduler.yaml
pkg/asset/templates/kubelet.yaml

It also seems some weren't prefixed with `v`, either way, it should be consistent.

pkg/asset: Update version metadata on manifests

---

hack/quickstart/.gitignore
hack/quickstart/README.md
hack/quickstart/init-master.sh
hack/quickstart/init-worker.sh
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker

The quickstart directory contains generic scripts / kubelet.service files which should work for a CoreOS node launched on various providers.
These scripts currently assume `/etc/environment` has been populated with `$COREOS_PUBLIC_IPV4` and `$COREOS_PRIVATE_IPV4`.
The initial guide in the README describes how to use these scripts on vanilla CoreOS nodes using GCE.
ref: https://github.com/coreos/bootkube/issues/32
/cc @philips @pbx0 @dghubble

hack: add quickstart scripts & initial GCE guide

---

hack/single-node/bootkube-up

This is to match multi-node. This was causing TLS errors because it
caused the user-data containing the kubeconfig to be updated on every
bootkube-up run, when it should only happen on the first run.

hack/single-node: Update bootkube-up to add kubeconfig once

---

pkg/asset/asset.go
pkg/asset/internal/templates.go
pkg/asset/k8s.go

Update kube-dns deployment from 11 to v17.1.
rel: https://github.com/coreos/coreos-kubernetes/commit/64e44562fd4da459d631d28f6269c22779372cca
replaces: #107
cc: @ericchiang

pkg/asset: Update kube-dns to v17.1

---

cmd/bootkube/start.go
hack/multi-node/bootkube-up
hack/single-node/bootkube-up
pkg/bootkube/bootkube.go
pkg/bootkube/create.go
pkg/bootkube/status.go

Basic status information goes to stdout and diagnostics/logs go to
stderr.
Running `bootkube start 2> /dev/null`gives the following output:
```
Running temporary bootstrap control plane...
Sending self-hosted assets to temporary control plane...
Spawning self-hosted control plane...
Pod Status: kube-controller-manager    	Pending
Pod Status:          kube-scheduler    	Pending
Pod Status:                 kubelet    	Pending
Pod Status:          kube-apiserver    	Pending
Pod Status:          kube-scheduler    	Running
Pod Status:          kube-apiserver    	Running
Pod Status:                 kubelet    	Running
Pod Status: kube-controller-manager    	Running
All self-hosted control plane components successfully started
Bootstrap complete. Access your kubernetes cluster using:
kubectl …
```

pkg/bootkube: add simple stdout status info

---

image/checkpoint/checkpoint-pod.yaml
pkg/bootkube/bootkube.go

During the provisioning of the cluster bootkube will be checking for running checkpointing pod to reduce the window on first boot where an api-server could fail and there is no checkpoint.
Fixes #117

Bootkube checks for active checkpointer pod.

---

cmd/checkpoint/main.go

@aaronlevy 
This is just the changes to the checkpointer code. Once thats merged we can build the checkpointer image and make the bootkube changes as well.
For https://github.com/kubernetes-incubator/bootkube/issues/127

remove the need to stagger apiserver ports

---

pkg/asset/internal/templates.go
pkg/bootkube/bootkube.go

followup to: https://github.com/kubernetes-incubator/bootkube/pull/144
@aaronlevy

pkg/bootkube: remove apiserver port staggering

---

cmd/bootkube/render.go
pkg/asset/asset.go
pkg/asset/k8s.go
pkg/bootkube/bootkube.go

` --self-host-kubelet=false` can be passed to the `bootkube render` command to disable to creation of the kubelet asset. The self-hosted kubelet will never be created and the system kubelet will remain functional this way.
`bootkube start` no longer requires the kubelet pod to be running before it exits since the cluster should be functional either way. This simplifies this PR but it is possible, in the future, that `requiredPods` might need to be specified or inferred from the rendered assets.

Kublet is optionally run as a self-hosted component

---

Documentation/upgrading.md

Same as https://github.com/coreos/coreos-baremetal/blob/master/Documentation/bootkube-upgrades.md, but without bare-metal or QEMU/KVM mentions.

Add self-hosted Kubernetes upgrade guide

---

cmd/bootkube/start.go
pkg/util/etcdutil/start_etcd.go

- add a feature flag that will enable self hosted etcd
- on self hosted etcd mode, create a etcd static pod have bootkube wait
until it's up

etcd: add self hosted etcd mode

---

pkg/asset/asset.go
pkg/asset/internal/templates.go
pkg/asset/k8s.go

Checkpointer deployed independently from api-server. Deploying it as a separate component so it can be upgraded independently.
fixes #161

Deploy checkpointer independently from api-server

---

cmd/checkpoint/main.go

Strips pod object of nonessential info. Its in [WIP] since these are few of the things that I could come up with to strip. If there are more let me know and I will add it to the function.
fixes #164

Stripping of nonessential info prior to checkpointing

---

pkg/asset/internal/templates.go

The label changes between versions don't work well with deployment
updates & this is the same change upstream has made during the switch
from replication-controller to deployment.

asset: Remove version info from dns addon

---

cmd/bootkube/render.go
cmd/bootkube/start.go
pkg/asset/asset.go
pkg/asset/internal/templates.go
pkg/asset/k8s.go
pkg/bootkube/bootkube.go
pkg/bootkube/status.go
pkg/util/etcdutil/migrate.go
pkg/util/etcdutil/start_etcd.go

This PR implements the migration process in self hosted etcd mode:
- starts etcd operator
- reserve etcd service with IP 10.3.0.15
- migrate static etcd pod to managed etcd clusterd
In Render:
```
$ _output/bin/linux/bootkube render --asset-dir=asset --etcd-servers=http://10.3.0.20:2379 --storage-backend=etcd3
```
In Start:
```
$ _output/bin/linux/bootkube start --asset-dir=asset --experimental-self-hosted-etcd=true
```
You might need to use "sudo" or get access to "/etc/kubernetes/manifest" dir.

self hosted etcd migration

---

cmd/bootkube/start.go
pkg/util/etcdutil/start_etcd.go

etcdServer is passed in in "bootkube start".
We should use it.

use etcd server from config

---

pkg/util/etcdutil/migrate.go
pkg/util/etcdutil/start_etcd.go

Self hosted spec is changed from etcd operator side.
Because we are now using host network, we can't conflict with self hosted etcd pods which use "2379" hard-coded right now, and we change the static etcd pod to use different ports.
"bootkube start":
```
$ _output/bin/linux/bootkube start --asset-dir=asset --experimental-self-hosted-etcd=true --etcd-server http://127.0.0.1:12379
```
We need to pass in etcd-server.

use self hosted spec and change static etcd pod

---

pkg/asset/internal/templates.go

For consistency all kubernetes components have the `k8s-app` label, for the `kube-proxy` this was previously not the case. This matches the upstream [example manifest](https://github.com/kubernetes/kubernetes/blob/8fd414537b5143ab039cb910590237cabf4af783/cluster/images/hyperkube/kube-proxy-ds.yaml) in terms of the `k8s-app` label. Let me know if you want me to adapt any other changes from the upstream manifest in here.
@aaronlevy

pkg/asset/internal: label key naming consistency

---

hack/quickstart/quickstart-gce.md
hack/tests/conformance-gce.sh

Fixes https://github.com/kubernetes-incubator/bootkube/issues/221

hack/GCE: use --image-family for CoreOS channel

---

cmd/checkpoint/README.md
cmd/checkpoint/main.go
cmd/checkpoint/main_test.go
image/checkpoint/checkpoint-pod.yaml
pkg/asset/internal/templates.go

Rewrite of the checkpointer to support checkpointing of arbitrary pods.
Will checkpoint pods based on annotation, then also supports garbage collection of pods and secrets by tracking the parents of the checkpoints. I've called out TODOs in the code for some minor tweaks that can be follow ups.
Big change, so hopefully can get a few eyes on this.
/cc @yifan-gu @xiang90 @ericchiang @dghubble @derekparker

checkpointer: rewrite for generic pod checkpoints

---

pkg/asset/internal/templates.go

* Respect names given to nodes, don't assume IP
* Allow DNS node names to be used
* kube-apiserver uses host's default iface for advertise-address
We're using this patch for bare-metal and AWS clusters to allow DNS names to be used. Kubernetes 1.4, introduced the `spec.nodeName` downward api field. Pods can make use of the node name which may be either an IP or a DNS name.
rel: #90

Use spec.nodeName as hostname-override, not podIP

---

hack/multi-node/user-data.sample
hack/quickstart/init-master.sh
hack/quickstart/init-worker.sh
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/single-node/user-data.sample
pkg/asset/asset.go
pkg/asset/internal/templates.go
pkg/asset/k8s.go
pkg/bootkube/bootkube.go

This change involves a switch to using the Container Network Interface (CNI) plugins for configuring the pod network. See the http://kubernetes.io/docs/admin/network-plugins/ for more information  on kubernetes + CNI plugin integration.
There is a known issue with using CNI plugins that setting a `hostPort` on a pod will no longer work. This is because the `hostPort` relies on docker to configure the host -> pod bridge, but in the case of CNI network plugins, docker does not know about the pod, network and the CNI plugin is used instead. 
See upstream issues for more information:
https://github.com/kubernetes/kubernetes/issues/23920
https://github.com/kubernetes/kubernetes/issues/31307
The most common place I've seen this being surfaced as an issue is with ingress controllers, which make …

Configure pod-network via flannel CNI daemonset

---

pkg/asset/internal/templates.go

This flag was removed in https://github.com/kubernetes-incubator/bootkube/pull/151, but looks like we do still need this in some cases.
The bootkube-apiserver was setting the correct endpoint record for the default kubernetes service (`kubectl get endpoint/kubernetes`). However, after bootkube exits, the self-hosted api-server will eventually overwrite the endpoint again -- and it was using the host's default interface, which is not routable in some cases (e.g. virtualbox).
There may be some other options here (e.g. why does bootkube apiserver use correct interface, but hostNetwork api-server pod does not) -- but going to revert this part of the change so we avoid the regression until we have a better option.
/cc @dghubble @quentin-m @bassam

asset: set the advertise address based on pod ip

---

pkg/asset/internal/templates.go

This commit represents a workaround for #262. By maintaining
a file lock while the API server is running (either temporary
or self-hosted), we prevent the self-hosted API server from
starting and trying to bind ports, until the temporary one is
stopped. Therefore, we avoid the loop where the self-hosted
API server would crash as soon as it is brought up due to the
ports already being bound by the stopping temporary server.
cc @aaronlevy

pkg/asset/internal: Introduce a Flock around the API server

---

hack/multi-node/Vagrantfile
hack/multi-node/bootkube-up

This is against yet to be merged code (https://github.com/kubernetes-incubator/bootkube/pull/259)
This is to help test that PR more easily.
Usage is:
```
cd hack/multi-node
rm -rf cluster
vagrant destroy -f
SELF_HOST_ETCD=true ./bootkube-up
```

hack/multi-node: Add option to launch with self-hosted etcd

---

hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker

Otherwise the conformance tests are still running Kubelet 1.5.1.

hack/quickstart: Bump Kubelet to 1.5.2

---

cmd/bootkube/render.go
hack/multi-node/Vagrantfile
hack/multi-node/etcd-cloud-config.yaml
hack/quickstart/init-master.sh
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/single-node/user-data.sample
hack/tests/conformance-gce.sh
pkg/asset/asset.go
pkg/asset/internal/templates.go
pkg/bootkube/bootkube.go

The existing `--storage-backend=etcd3` parameter can lead to unexpected
and confusing behavior when used without the experimental self-hosted
etcd (`--experimental-self-hosted-etcd=true`) or with the examples.
When specified, Bootkube runs the temporary control plane against etcd
v2 and then the self-hosted plane using etcd v3. However, etcd uses two
separate data stores for v2 and v3 APIs (https://git.io/v1NxV).
Therefore when the transition occurs after the self-hosted control plane
has been created, everything basically disappears.
Instead of adding yet another flag to Bootkube to enable etcd3 with the
temporary control-plane, this commit makes a leap forward and use etcd3
as the default storage backend for both control-planes, which will be the 
default in Kubernetes 1.6.
**Note: This …

Use etcd3 for both the temporary and self-hosted control planes

---

pkg/bootkube/bootkube.go

In some environments, pulling image from `gcr.io` is faster than `quay.io`. We might call `etcdutil.Migrate()` too early even before `etcd-operator` got started.
In this case, the user will have `fail to wait etcd TPR to be ready: timed out waiting for the condition` error and the bootstrap process got terminated.
This PR add `etcd-operator` to `requiredPods` when `selfHostedEtcd` is true. We'll make sure `etcd-operator` is running before calling `etcdutil.Migrate()`.  Making the bootstrap process less likely to fail.

Add etcd-operator to requiredPods when selfHostedEtcd is true

---

pkg/bootkube/bootkube.go

I was consistently hitting this timeout during development - bump it to give a little more wiggle room. We could be a little more intelligent about this in the future.

pkg/bootkube: increase timeout for asset creation

---

pkg/asset/internal/templates.go
pkg/util/etcdutil/migrate.go
pkg/util/etcdutil/start_etcd.go

Reverts kubernetes-incubator/bootkube#306
We have the problem of incompatible client-go versions.
We need to keep using the old version of image until we figure out the solution.

Revert "self hosted etcd: bump version"

---

hack/tests/conformance-gce.sh
hack/tests/conformance-test.sh

Forgot to update this when merging the tls bootstraping feature. 
cc @Quentin-M

hack/tests: update conformance scripts for tls-bootstraping

---

pkg/bootkube/bootkube.go
pkg/bootkube/parse.go
pkg/bootkube/parse_test.go

* Temporary apiserver should use service CIDR detected from `kube-apiserver.yaml`
* Temporary controller-manager should use pod CIDR detected from `kube-controller-manager.yaml`
* Eliminates the need for coordination btw render and start and unblocks pod/service CIDR customization
Full discussion about why we're taking this approach over others: https://github.com/kubernetes-incubator/bootkube/issues/236#issuecomment-279797787
related. #236
Missing assets:
```
$ bootkube start --asset-dir=empty
Error: can't read file manifests/kube-apiserver.yaml: open empty/manifests/kube-apiserver.yaml: no such file or directory
can't read file manifests/kube-apiserver.yaml: open empty/manifests/kube-apiserver.yaml: no such file or directory
```
kube-apiserver.yaml (or controller manager) named …

Detect pod and service CIDR from manifests

---

pkg/asset/tls.go

nit: Organization kube-aws is from the kube-aws era. The old name can cause user confusion.

pkg/assets/tls: Update organization name

---

hack/multi-node/user-data.sample
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/single-node/user-data.sample

This PR changes the cloud-config data in the hack dir so that it
stores the rkt UUID for the kubelet pod, and gc the stopped ones.
Fix #218 
/cc @aaronlevy @derekparker @pbx0

hack/*: GC kubelet rkt images after run.

---

cmd/bootkube/render.go
cmd/bootkube/render_test.go
hack/multi-node/Vagrantfile
pkg/asset/asset.go
pkg/asset/internal/templates.go
pkg/asset/k8s.go
pkg/asset/tls.go
pkg/bootkube/bootkube.go
pkg/bootkube/parse.go
pkg/bootkube/status.go
pkg/util/etcdutil/migrate.go

u* Add cmd flags --pod-cidr and --service-cidr
* Pick an appropriate apiserver service IP, DNS Service IP, and etcd Service IP (experimental) from the service range
Fixes/unblocks/replaces #236 #245 #250
Default (same behavior).
```
bootkube render --asset-dir=assets --api-servers=https://node1.example.com:443 --api-server-alt-names=DNS=node1.example.com
Writing asset: assets/manifests/kube-scheduler.yaml
...
```
Customize the pod or service CIDR range.
```
bootkube render --asset-dir=assets --api-servers=https://node1.example.com:443 --api-server-alt-names=DNS=node1.example.com --pod-cidr 10.2.1.1/16 --service-cidr 10.33.1.200/16
You have selected a non-default service CIDR 10.33.0.0/16 - be sure your kubelet service file uses --cluster-dns=10.33.0.10
Writing asset: …
```

pkg,cmd: Add Kubernetes pod and service CIDR customziation

---

cmd/checkpoint/main_test.go

This was causing extra noise when building images. There is a line in the makefile when building that runs `find . -name vendor -prune -o -name '*.go' -exec gofmt -s -d {} +`
cc @aaronlevy

cmd/checkpoint: run gofmt -w -s

---

pkg/asset/asset.go
pkg/asset/internal/templates.go
pkg/asset/k8s.go
pkg/asset/tls.go
pkg/bootkube/bootkube.go
pkg/tlsutil/tlsutil.go

RBAC changes pulled out of #261.
~~Still seeing errors bringing up the API server. Don't know what it's about~~
edit: didn't give my VMs enough disk :/
```
Feb 23 01:06:01 node1.example.com kubelet-wrapper[1178]: E0223 01:06:01.408544    1178 pod_workers.go:184] Error syncing pod c61279d9-f963-11e6-b0d5-525400a19cae, skipping: failed to "StartContainer" for "kube-apiserver" with CrashLoopBackOff: "Back-off 20s restarting failed container=kube-apiserver pod=kube-apiserver-0wr35_kube-system(c61279d9-f963-11e6-b0d5-525400a19cae)"
Feb 23 01:06:01 node1.example.com kubelet-wrapper[1178]: E0223 01:06:01.739433    1178 secret.go:197] Couldn't get secret kube-system/kube-apiserver
```

pkg: re-enable RBAC

---

cmd/checkpoint/README.md
cmd/checkpoint/main.go
cmd/checkpoint/main_test.go

Add support for configmap in checkpointer

---

hack/quickstart/quickstart-gce.md

One of the example commands was using a hard-coded filter instead of `CLUSTER_PREFIX`

Update gce quickstart to use CLUSTER_PREFIX always

---

Documentation/upgrading.md
RELEASING.md
hack/multi-node/user-data.sample
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/single-node/user-data.sample

This fixes #207. 
The following environment variables used by kubelet-wrapper have been
deprecated:
* `KUBELET_VERSION` has been replaced with `KUBELET_IMAGE_TAG`
* `KUBELET_ACI` has replaced with `KUBELET_IMAGE_URL`
* `RKT_OPTS` has been replaces with `RKT_RUN_ARGS`
See https://github.com/coreos/coreos-overlay/blob/build-1220/app-admin/kubelet-wrapper/files/kubelet-wrapper#L29-L39.

Replace deprecated env vars passed to the kubelet-wrapper

---

hack/multi-node/user-data.sample
hack/quickstart/init-master.sh
hack/quickstart/init-worker.sh
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/single-node/user-data.sample
pkg/asset/internal/templates.go
pkg/bootkube/bootkube.go

This PR turns on kubelet authentication[0], restricting access to the kubelet API running on port 10250. API servers deployed by bootkube now use a client cert to issue requests to this API (used for exec, logs, and port-forward functionality).
Because kubelets don't have a way to bootstrap a serving certificate with the correct SANs in many deployments (e.g. an autoscaling group), we'll continue to omit the API server CA check on the kubelet. We hope to remedy this later with TLS bootstrapping[1] once the kubelet can request a serving cert.
On the kubelet side, deployments should enable the following flags on the kubelet:
```bash
--client-ca-file=/etc/kubernetes/ca.crt # Placed in assets/tls/ca.crt by 'bootkube render'
--anonymous-auth=false
```
If these flags aren't enabled, the kubelet …

use a client cert for API server to kubelet communication

---

pkg/asset/asset.go
pkg/asset/internal/templates.go
pkg/asset/k8s.go

`kenc` is an iptables checkpoint tool.
With it, service IP connectivity on master nodes can endure reboot.

SelfHostedEtcd: Add kenc as DS in master nodes

---

hack/quickstart/init-master.sh
hack/quickstart/init-worker.sh
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/tests/conformance-gce.sh

Add support for self-hosted etcd within master-init script. Simplify service files and init-worker script a bit which makes them easier to configure and re-use by other tools. 
cc @aaronlevy

support self-hosted etcd in quickstart scripts

---

pkg/bootkube/create.go

Instead of trying to handle the NotFound error, check that the kube-system namespace exists before attempting to create assets.
This fixes #319.

Wait for kube-system namespace before creating assets

---

cmd/bootkube/render.go

Automatically set —etcd-servers to —service-cidr base IP + 15.
For example, if —service-cidr=10.42.0.0/24, —etcd-servers=http://10.42.0.15:2379.
Fixes https://github.com/kubernetes-incubator/bootkube/issues/329

cmd/render: Infer etcd-servers from service-cidr for self-hosted etcd

---

pkg/asset/internal/templates.go

kenc updates:
- atomically write iptables checkpoint file
etcd-operator updates:
- fix self hosted etcd reboot issues (relies on etcd pod not failing and endpoint not deleted)
- fix an issue that for-looping showing `etcd health probing failed for xxx: context deadline exceeded`
fix https://github.com/kubernetes-incubator/bootkube/issues/373
This would help us enable CI destruction test suite and pass them.
Note that this is not the ideal solution. We will need to do more testing as talked in https://github.com/kubernetes-incubator/bootkube/issues/379 .

SelfHostedEtcd: update etcd-operator and kenc

---

cmd/bootkube/render.go

Fixes https://github.com/kubernetes-incubator/bootkube/issues/275

cmd/render: Rename —self-host-kubelet to —experimental-self-hosted-kublet

---

hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker

This was already done in the other setup methods, but never done for quickstart. v1.6.0 will hard fail if this flag isn't updated so might as well do it now.

hack/quickstart: remove deprecated flag

---

Makefile
pkg/asset/internal/templates.go
vendor/github.com/coreos/etcd-operator/pkg/spec/backup.go
vendor/github.com/coreos/etcd-operator/pkg/spec/cluster.go
vendor/github.com/coreos/etcd-operator/pkg/spec/cluster_tls.go

There is an issue w.r.t. scaling down that we fixed in 0.2.4:
https://github.com/coreos/etcd-operator/issues/900

etcd_operator: bump image and vendor version to 0.2.4

---

hack/quickstart/quickstart-aws.md

The correct source-group name should be `${CLUSTER_PREFIX}-sg`
Also replace `k8s` with `${CLUSTER_PREFIX}` in other places.
/cc @aaronlevy

docs: fix typo in quickstart-aws.md

---

cmd/checkpoint/README.md
cmd/checkpoint/main.go
cmd/checkpoint/main_test.go
image/checkpoint/Dockerfile
image/checkpoint/build-image.sh
image/checkpoint/checkpoint-install.sh
pkg/asset/asset.go
pkg/asset/internal/templates.go

This PR enables us to GC itself using the existing codepath.
Also it removes the needs for the checkpoint-installer, which
also enables us to update the checkpointer by just updating the
checkpointer's manifest.

Checkpoint and activate itself.

---

hack/tests/conformance-gce.sh

The latest gcloud installer scripts will break the test, so let's pin to an old version.

conformance-gce.sh: Pin to a particular gcloud installer version.

---

hack/single-node/bootkube-up
hack/single-node/user-data-etcd.sample
hack/single-node/user-data.sample
pkg/bootkube/bootkube.go
pkg/bootkube/parse.go

This adds the self-hosted etcd cluster to the temporary control plane
config, which should hopefully mitigate situations where the control
plane loses contact with etcd during the boot-etcd -> self-hosted-etcd
pivot and gives up leader status as a result.
I also fixed the hack/single-node config to not start local etcd
when running with self-hosting.
Fixes #411.

Fix apiserver etcd-servers flag when self-hosting.

---

RELEASING.md
hack/quickstart/init-master.sh
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/tests/conformance-gce.sh

With this PR, we don't have to update the quickstart scripts after a release is cut.
Also we are able to run conformance test for bootkube with corresponding kubelet version.

hack/*, RELEASE.md: Use local static binary for quickstart and conformance test.

---

hack/quickstart/init-master.sh

A simple fix because the bootkube is not running in rkt container now.

hack/quickstart/init-master.sh: Fix bootkube command.

---

cmd/checkpoint/README.md
cmd/checkpoint/main.go
hack/multi-node/user-data.sample
hack/quickstart/kubelet.master
hack/single-node/user-data.sample
image/checkpoint/checkpoint-pod.yaml
pkg/asset/internal/templates.go

Using `/srv/kubernetes` is less intuitive, everything else lives under `/etc/kubernetes`, and it's possible the two mounts could be different filesystems which defeats the purpose of using an atomic `mv` internally.
This patch moves "inactive" checkpointed manifests to `/etc/kubernetes/inactive-manifests`.

Use /etc/kubernetes/inactive-manifests instead of /src/kubernetes/manifests

---

pkg/asset/internal/templates.go

* Use /etc/kubernetes/inactive-manifests instead of
/srv/kubernetes/manifests.

pkg/asset: Bump pod-checkpointer

---

pkg/asset/internal/templates.go

This commit adds antiaffinity rules to the controller manager and the
sheduler to ensure that these deployments' pods do not all end up on the
same master node, especially now that they are pinned with node
selectors. To make this possible on small clusters, e.g. those with 1
master node, this is specified with "preferred" rather than "required".
This is a reopening of https://github.com/kubernetes-incubator/bootkube/pull/298.
cc @aaronlevy

templates: ensure critical components dont coexist

---

pkg/asset/internal/templates.go

For more information: https://kubernetes.io/docs/concepts/cluster-administration/guaranteed-scheduling-critical-addon-pods/.
Since the hack setups (and I believe all cluster setups) only use a single master we could run the rescheduler, however for this PR I am not including it as we have concerns over the rescheduler not being leader elected, and potential issues with multi-master setups. See https://github.com/kubernetes/contrib/issues/2551.

pkg/asset: Add critical pod annotations to control-plane

---

Documentation/upgrading.md
hack/multi-node/bootkube-up
hack/multi-node/user-data.sample
hack/quickstart/kubelet.master
hack/single-node/user-data.sample
pkg/asset/internal/templates.go
pkg/util/etcdutil/migrate.go

Update the master node label from `master` to
`node-role.kubernetes.io/master` as documented in
https://github.com/kubernetes/kubernetes/pull/39112.
cc @aaronlevy @yifan-gu

hack,templates: rename `master` node label

---

pkg/asset/asset.go
pkg/bootkube/bootstrap.go

This reduces the number of paths that users need to make available to
bootkube, especially if running in a container.
I think this is a good change because the user only needs to guarantee
read/write access to one path (/etc/kubernetes) rather than two.

Change temporary secrets path to /etc/kubernetes/bootstrap-secrets.

---

Makefile
vendor/github.com/coreos/etcd-operator/pkg/spec/cluster.go
vendor/github.com/coreos/etcd-operator/pkg/spec/etcd_cluster_list.go

Fixes https://github.com/kubernetes-incubator/bootkube/issues/439
We should just apply the vendoring patch as part of the vendoring process itself. If it's done at compile time the working tree will report as dirty.

Patch etcd-operator as part of vendoring process

---

pkg/asset/internal/templates.go

We no longer use alpha API groups by default in bootkube, so we should
stop enabling them by default, allowing us to be confident that we do
not rely on alpha features.
cc @aaronlevy

templates: stop enabling alpha API groups

---

hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker

This flag has been deprecated for a few releases. There are other flags
with reasonable defaults that supercede this behavior.
Fixes #404.

Remove deprecated --minimum-container-ttl-duration.

---

hack/multi-node/bootkube-up
hack/multi-node/user-data.sample
pkg/asset/internal/templates.go

This PR adds taints and tolerations to the bootkube templates to ensure that node workloads do not get scheduled on master nodes.
cc @aaronlevy @yifan-gu

templates: add toleration to control-plane components

---

hack/multi-node/user-data.sample
hack/quickstart/kubelet.master

getting error
```
Error: invalid argument "node-role.kubernetes.io/master:NoSchedule" for --register-with-taints=node-role.kubernetes.io/master:NoSchedule: invalid taint spec: node-role.kubernetes.io/master:NoSchedule
```
I found that the taint was missing the taint value. It needed a `=` so that the value is set to empty string `""`.
Fixes @Quentin-M's issues in https://github.com/kubernetes-incubator/bootkube/pull/434.

hack: fix taint value

---

pkg/asset/internal/templates.go

Change the toleration operator from `Equal` to `Exists` for all `node-role.kubernetes.io/master` tolerations.

templates: change toleration operator

---

hack/multi-node/user-data.sample
hack/quickstart/kubelet.master

Drop the taints on master nodes until fix for https://github.com/kubernetes-incubator/bootkube/issues/452 is merged.
/cc @xiang90 @hongchaodeng

hack: remove taints from master node

---

pkg/asset/internal/templates.go

fixes https://github.com/kubernetes-incubator/bootkube/issues/454

pkg/asset: bump flannel to v0.7.1

---

cmd/bootkube/start.go
pkg/asset/asset.go
pkg/asset/internal/templates.go
pkg/bootkube/bootkube.go
pkg/bootkube/create.go
pkg/bootkube/parse.go
pkg/bootkube/status.go
pkg/util/etcdutil/migrate.go

This disables the insecure apiserver port for both the bootstrap
and self-hosted control planes. In so doing I migrated all of bootkube
to use the kubeconfig rather than a static local port.
This assumes that the temporary control plane is also addressable
at the same IP as the the final control plane. If this is a faulty
assumption then this part likely won't work.
While I was at it I changed some dependencies to point at client-go
to help us move off of vendoring all of kubernetes in the future.
Fixes #324.

Disable insecure apiserver access.

---

pkg/asset/internal/templates.go

This should ensure that the bootstrap apiserver advertises itself
on the same interface as the kubelet (since hostnetwork = true)
rather than an arbitrary one.
Fixes #453.

Add `--advertise-address` to bootstrap-apiserver manifest.

---

hack/multi-node/etcd-cloud-config.yaml
hack/multi-node/user-data.sample
hack/quickstart/init-master.sh
hack/quickstart/kubelet.master
hack/single-node/user-data-etcd.sample
pkg/asset/internal/templates.go
pkg/util/etcdutil/migrate.go

This PR is to update image versions of etcd-operator, etcd.
The latest etcd-operator release also fixes scale test, reboot test due to 1.6 upgrade.

*: update etcd-operator and etcd version

---

pkg/asset/internal/templates.go

This contains the changes for keeping the checkpointed pod labels: https://github.com/kubernetes-incubator/bootkube/pull/443

pkg/asset: Bump pod-checkpointer image version

---

pkg/asset/internal/templates.go

~This was a solution to #463, not necessarily the right solution. I'm not familiar with the original reasons we set `configure-cloud-routes=true` to false (upstream default is true) or its impact on other providers.~
* Add --cloud-provider to bootstrap apiserver and controller-manager (missing)
~* Set --configure-cloud-routes true. Upstream description: "Should CIDRs allocated by allocate-node-cidrs be configured on the cloud provider. (default true)"~

pkg/asset/internal: Add --cloud-provider to bootstrap manifests

---

cmd/bootkube/main.go
cmd/bootkube/start.go

- Use the same logging config for all bootkube commands.
- Make sure flag.Parse() is called, otherwise glog complains.
I checked and cobra does not call flag.Parse().

Fix up some logging configuration.

---

cmd/checkpoint/main.go

The apiParentPods is always non-nil, so we should test the length
instead of the nil pointer. Besides, testing the length will work
for nil pointer as well.

checkpoint: Fix garbage collection bug.

---

pkg/asset/internal/templates.go

Harmless, but apiVersion is included twice in the ClusterRoleBinding. I noticed while doing some diffs with other renderings.

pkg/assets/internal: Remove duplicated apiVersion

---

hack/terraform-quickstart/README.md
hack/terraform-quickstart/main.tf
hack/terraform-quickstart/outputs.tf
hack/terraform-quickstart/start-cluster.sh
hack/terraform-quickstart/terraform.tfvars.example
hack/terraform-quickstart/variables.tf

This adds a basic way to use terraform to setup AWS compute along with the
quickstart scripts to initiate a cluster. This is designed for forming
the basis for test setup.

hack/terraform-quickstart: initial commit

---

pkg/asset/internal/templates.go

There is a change for self hosted etcd pods that make it more resilient
on anti-affinity guarantee. It doesn't break existing cluster, but have
stronger guarantee.

templates: update etcd-operator to v0.2.6

---

README.md
cmd/bootkube/recover.go
hack/multi-node/bootkube-recover
hack/multi-node/bootkube-test-recovery
pkg/bootkube/bootkube.go
pkg/bootkube/bootstrap.go
pkg/bootkube/create.go
pkg/recovery/etcd.go
pkg/recovery/recover.go
pkg/recovery/recover_test.go
pkg/recovery/util.go

The new `bootkube recover` command provides a framework for reading
control plane manifests out of a storage backend, serializing them to
disk, and constructing pod manifests for the bootstrap components that
are usable with `bootkube start` to re-bootstrap the control plane.
The command initially provides and etcdclient backend for use with a
running etcd cluster. In the future we can add support other methods,
such as an etcd backup directory or a running apiserver.
There is also documentation and an example script in hack/multi-node
that deletes a master node, recovers the assets from etcd, and then
re-bootstraps the control plane.
This is a first step in addressing the issues described in #432.

Preliminary recovery command for bootkube.

---

pkg/recovery/etcd.go
pkg/recovery/recover.go
pkg/recovery/recover_test.go

This change also extracts and fixes up `ConfigMaps`.
It does not support the per-config-map mode bits that
`ConfigMapVolumeSource` supports.

Add recovery support for ConfigMaps.

---

pkg/bootkube/create.go

If we do not increase this count, we will hit the error returns at line 132 in the same file.
Found when trying out recovery from a self hosted etcd cluster.
/cc @yifan-gu @aaronlevy

pkg/bootkube: increase count when api object already exists

---

README.md

* Link to matchbox, not coreos-baremetal (old name)
* Link to the terraform-based example which is easier for newcomers

README.md: Update bare-metal docs link to matchbox

---

pkg/asset/internal/templates.go

All system components are sitting on master nodes.
However, etcd operator was somehow dismissed for that.

templates: etcd operator should select master nodes

---

cmd/bootkube/render.go

v0.3.0 supports per cluster S3 policy and dynamically change backup
policy.
This is needed for disaster recovery.

*: update etcd-operator image to v0.3.0

---

e2e/main_test.go
e2e/node.go
e2e/ssh_client.go

Calling GetCluster() in each test can returns a Cluster type that
stores the list of master and worker nodes, which provide SSH() and
Reboot() interfaces.

e2e: Add simple cluster type to make tests migration easier.

---

pkg/util/etcdutil/migrate.go

Since the etcd pivot just occurred the apiserver may be temporarily
unavailable. This retries until successful or timeout, but still doesn't
fail the entire process on failure.

Add retry loop to removing bootstrap etcd service.

---

pkg/asset/internal/templates.go

This migrates all self-hosted components as possible to run as non-root.
The main exception for now is the apiserver, which has a complication
due to its need to bind a low port:
https://github.com/kubernetes/kubernetes/issues/46148

Make as many components as possible run as non-root.

---

e2e/etcdscale_test.go
e2e/main_test.go

Translated from the pluton equivalent test. Added expectedMasters flag as a hint so that the test knows to either block on waiting for more masters to show up or skip the test if there isn't enough masters and we aren't expecting more.
cc @aaronlevy @yifan-gu

e2e: add etcd scaling test

---

pkg/asset/internal/templates.go

By convention the primary container should match the name of the
daemonset.

Fix pod-checkpointer container name.

---

hack/quickstart/init-master.sh

The binary is ~80 MB. Enabling compression speeds up the quickstart for
"typical" internet connections with << 100 Mbps.

quickstart: Compress binary when sending to nodes

---

hack/multi-node/user-data.sample
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/single-node/user-data.sample

Otherwise the kubelet-pod.uuid won't survice the reboot, which makes
`ExecStartPre=-/usr/bin/rkt rm` meaningless.

hack/*: Put kubelet-pod.uuid into a less volatile place.

---

pkg/asset/images.go
pkg/asset/internal/templates.go

This changes the self hosted etcd pods to use FQDN:
```
${member-name}.${cluster-name}.${namespace}.svc.cluster.local
```
We also need to change the bootstrap etcd pod to use cluster DNS.
In order to survive reboot, we update kenc to checkpoint etcd hosts onto
/var/etcd (where etcd data-dir resides).

*: bump etcd-operator to 0.3.2

---

pkg/recovery/recover.go
pkg/recovery/recover_test.go

Bootstrapping relies on the bootstrap pods running as root so they can
access files on the host machine. Bootkube now runs self-hosted pods as
non-root, so recover needs to strip the security context when outputting
bootstrap manifests.
Fixes #576 
cc @abourget

recover: fix security contexts for bootstrap pods.

---

README.md
cmd/bootkube/recover.go
hack/multi-node/bootkube-test-recovery
hack/multi-node/bootkube-test-recovery-self-hosted-etcd

Field ops reports that people find the --asset-dir flag confusing; they
think that means you need to pass in the same --asset-dir that was used
to create the cluster.
cc @coresolve

Change `bootkube recover` flag to --recovery-dir.

---

cmd/bootkube/render.go
e2e/network_test.go
hack/multi-node/bootkube-up
hack/multi-node/user-data.sample
hack/quickstart/init-master.sh
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/single-node/bootkube-up
hack/single-node/user-data.sample
hack/terraform-quickstart/outputs.tf
hack/terraform-quickstart/start-cluster.sh
hack/terraform-quickstart/variables.tf
pkg/asset/asset.go
pkg/asset/images.go
pkg/asset/internal/templates.go
pkg/asset/k8s.go

#513 
Notes:
- Uses Calico's Kubernetes Datastore  [`installation`](http://docs.projectcalico.org/v2.2/getting-started/kubernetes/installation/hosted/kubernetes-datastore/) to provide policy only support
Needs to be discussed:
hyperkube image already ships with cni binaries in `/opt/cni/bin` and kube-calico DaemonSet also installs its cni binaries in `/opt/cni/bin`.
So there would be chances of version mismatch as kubelet doesn't mount this directory from host. To prevent this I have mounted an empty `/opt/cni/bin` from the host to the kubelet.

Calico policy support

---

pkg/recovery/etcd_template.go

Current master is broken on self-hosted etcd recovery. We need this to fix it.
@diegs @aaronlevy @xiang90

*: bootFromBackupEtcd should use `dnsPolicy: ClusterFirstWithHostNet`

---

hack/terraform-quickstart/main.tf
hack/terraform-quickstart/network.tf
hack/terraform-quickstart/terraform.tfvars.example
hack/terraform-quickstart/variables.tf

This PR avoids terraform depending on a sane default network existing to
expose the nodes. This includes creating a VPC, subnet, route table,
internet gateway, open security group, and a network ACL.  This will be
useful once tools to auto-wipe a region are used so that it doesn't take
out all our tests that depend on default networks lying around.
Besides changing the variable `instance_tags` to `resource_owner` to tag our resources this should ultimately be creating nodes that are no different from before. As an aside, we should probably conform to the new tagging standard, but since most uses of this terraform are transient anyway its not urgent.
Also, its important we get this in tomorrow or CI will likely break.
cc @aaronlevy

hack/terraform-quickstart: remove dependancy on default network

---

e2e/ssh_client.go

The ergonomics could be improved a bit (not all tests have ready access
to the list of hostnames), but that is more in-scope for other
framework-ish cleanups.
Posting this up while I wait for flakes to reproduce locally.
cc @diegs @yifan-gu

e2e: add ability to drop out of test and into SSH shell

---

e2e/etcdscale_test.go
e2e/network_test.go
e2e/smoke_test.go

Previously if the wget-pod, for example, was never running all we saw was the phase "Failed" -- but no reason why it failed. We should output a bit more info to help debugging flaky PR tests.

e2e: flake / debug improvements

---

pkg/asset/internal/templates.go

For HA setup, enabling quorum-read is necessary.

templates: enable etcd-quorum-read in apiserver

---

cmd/checkpoint/main.go
cmd/checkpoint/main_test.go

This could lead to a race where the pod is not running and therefore
the checkpoint isn't created, but the lack of checkpoint leaves us
vulnerable to a service disruption.
Theoretically the apiserver reconciliation loop should handle cleaning
the checkpoint up.

pod-checkpointer: remove isRunning check.

---

pkg/bootkube/bootstrap.go

Fixes a file descriptor leak within the copyFile. The function leaks two handles for every file copied.
Close the handles after the copy.

copyFile: close source and destination file handles

---

e2e/node.go
hack/multi-node/README.md

This tweak allows for E2E tests to be ran with the multi-node config.
Trying to debug into the test flakiness with: https://github.com/kubernetes-incubator/bootkube/pull/674

run e2e locally

---

hack/quickstart/init-master.sh
hack/quickstart/init-node.sh

update-engine was initially masked to prevent the servers from
rebooting, when testing.
This caused locksmithd to restart forever and spam the system log,
as it depend on the update-engine.
With this change, the system would update but won't reboot
automatic.

hack/quickstart: Mask locksmithd instead of update-engine

---

Documentation/users-integrations.md
README.md

I'd still like to gather a few more use-cases before initial merging. This is to get the scaffolding started.
Also on the table is what info we want to collect RE production users (can use etcd as a reference: https://github.com/coreos/etcd/blob/master/Documentation/production-users.md)

Documentation: Add integration & production user tracking docs

---

pkg/asset/images.go

I haven't tested it, but @dghubble has [tested it with bootkube](https://github.com/coreos/flannel-cni/pull/3#pullrequestreview-57941938).

flannel-cni: bump to v0.2.0

---

pkg/asset/internal/templates.go

An incubator project probably shouldn't have this enabled by default.

pkg/asset: Disable etcd-operator analytics

---

pkg/asset/tls.go
pkg/tlsutil/tlsutil.go

Moves `bootkube` to the `OrganizationalUnit` and uses a UUID for the
`Organization`. This ensures that each CA's identifiers hash to a unique
value.
Fixes #696
cc @brianredbeard

x509: ensure unique certificate subjects.

---

pkg/asset/images.go
pkg/asset/internal/templates.go

Bump flannel-cni to [v0.3.0](https://github.com/coreos/flannel-cni/releases/tag/v0.3.0), but retain the original flannel CNI config name. This should make no functional change in clusters and should pass tests since flannel-cni:v0.3.0 is [compatible](https://github.com/coreos/flannel-cni/pull/5#issuecomment-328663841) with prior versions.
Then, we can either merge this and followup with #697 or skip and go directly to an updated #697 which changes the CNI config to add portmap.
I've tested a bare-metal cluster with this change.

pkg/asset: Update flannel-cni from v0.2.0 to v0.3.0

---

pkg/asset/internal/templates.go

With this change, hostPort is finally working.
Fix #662
---
Require: https://github.com/coreos/flannel-cni/pull/5 (due to the file extension change).
cc @aaronlevy 
I have tested this on my bootkube cluster.

CNI: Enable portmap plugin by default

---

e2e/network_test.go

* Calico DaemonSet is named calico-node, not kube-calico
Before:
```
[669905.121365] golang[5]: --- SKIP: TestNetwork (0.01s)
[669905.121659] golang[5]: 	network_test.go:34: kube-calico daemonset is not installed
```
After
```
[1193097.434229] golang[5]: === RUN   TestNetwork
[1193109.676259] golang[5]: === RUN   TestNetwork/DefaultDeny
[1193120.880809] golang[5]: === RUN   TestNetwork/NetworkPolicy
[1193127.124359] golang[5]: --- PASS: TestNetwork (29.69s)
[1193127.124911] golang[5]:     --- PASS: TestNetwork/DefaultDeny (11.20s)
[1193127.125206] golang[5]:     --- PASS: TestNetwork/NetworkPolicy (6.10s)
```

e2e: Fix network test to condition on calico-node

---

cmd/bootkube/render.go
hack/quickstart/init-master.sh
hack/terraform-quickstart/outputs.tf
hack/terraform-quickstart/start-cluster.sh
hack/terraform-quickstart/variables.tf
pkg/asset/asset.go
pkg/asset/k8s.go

* Canal is a setup that uses flannel for network connectivity and adds manifests for Calico in policy-only mode (i.e. user supplied networking)
* Rearranges flags as this was said to be desired before merging Calico support #714 
Author's note: I'd recommend users choose `--network-provider=calico` (added in #714) or stick with `--network-provider=flannel`. There are [known issues](#698) with choosing `experimental-canal` (flannel with Calico run in policy-only mode).

pkg: Move experimental-network-policy to network-provider canal

---

Documentation/upgrading.md

Upgrade docs taken from https://github.com/coreos/matchbox/blob/master/Documentation/bootkube-upgrades.md, but polished a bit for kubernetes-incubator/bootkube.
Closes #673

Documentation: Refresh the cluster upgrade guide

---

cmd/bootkube/render.go
hack/quickstart/init-master.sh
pkg/asset/asset.go
pkg/asset/internal/templates.go
pkg/asset/k8s.go

* Support choosing Flannel or Calico networking (`--network-provider`)
* On Jenkins, I've added a new test to provision a cluster with calico and perform the usual e2e tests.
This is based on [poseidon/bootkube-terraform](https://github.com/poseidon/bootkube-terraform), which uses Calico or flannel as the network provider on [AWS, GCE, and bare-metal clusters](https://github.com/poseidon/typhoon) (Digital Ocean w caveats). I figured it would be nice to have in the upstream project in case others want to use it.
rel #405 
Closes #407

Add network provider option and Calico support

---

README.md

The design proposals were organized according to SIGs in https://github.com/kubernetes/community/pull/1010. This led to a broken link.

README: fix link to design proposal

---

.travis.yml
build/build-release.sh
hack/tests/conformance-gce.sh
hack/tests/conformance-test.sh

Just to be extra sure. Also adds 1.9 to .travis.yml to increase build
coverage.

golang: bump to 1.8.4 everywhere.

---

cmd/checkpoint/main.go

Secrets and config maps are now pulled whenever the pod has changed or
after a timeout period whichever comes first.

Change polling frequency to reduce number of apiserver requests

---

cmd/bootkube/render.go

* Rename self-hosted-kubelet flag to force users to take notice, but provide a window to migrate
* Phase 1 of #735

cmd/bootkube: Mark --self-hosted-kubelet deprecated

---

pkg/asset/images.go

Initial testing for https://github.com/coreos/flannel/releases/tag/v0.9.0
cc @squeed

pkg/assets: Update flannel from v0.8.0 to v0.9.0

---

pkg/asset/internal/templates.go

* https://github.com/kubernetes/kubernetes/pull/53604
* Upstream fixed this on master, but it wasn't important enough to be backported. We should still pick it up since its easy enough on our side

Add --no-negcache to dnsmasq args

---

hack/multi-node/user-data.sample
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/single-node/user-data.sample
hack/tests/conformance-test.sh
pkg/asset/images.go

Updated the conformance test job to use kubernetes/kubernetes when launching conformance clusters.
The rkt flag `--insecure-options=image` isn't as scary as it sounds. rkt had different ideas about image security and originally required GPG signed ACIs. When pulling `docker://` images, those signatures aren't present which is why rkt calls them insecure. In a post-OCI world, it doesn't have so much weight.
Closes #744

Switch from quay.io to gcr.io hyperkube image

---

hack/multi-node/user-data.sample
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/single-node/user-data.sample
hack/tests/conformance-test.sh
pkg/asset/images.go

Builds atop #745 to update to `gcr.io/google_containers/hyperkube:v1.8.2`.
* v1.8.2 has fixes for apiserver memory leak issues

Update hyperkube from v1.8.1 to v1.8.2

---

cmd/bootkube/render.go

There is no `bootkube run` command as the ouputed message suggested, so
this replaces it with `bootkube start` to avoid confusion.

cmd: Change command suggestion message

---

pkg/checkpoint/apiserver.go
pkg/checkpoint/checkpoint.go
pkg/checkpoint/manifest.go
pkg/checkpoint/pod.go
pkg/checkpoint/process.go
pkg/checkpoint/process_test.go
pkg/checkpoint/runtime_service.go
pkg/checkpoint/state.go
pkg/checkpoint/state_test.go

This implements an explicit state machine to capture the various states
a checkpoint can be in. It recovers those states from disk upon startup
(if applicable) and then reconciles them with the states that are
fetched from the various apiservers.
It also adds 2 new states to attempt to workaround issues with
kubernetes 1.8 in which daemonset pods are deleted before being
recreated. For single-master clusters this can lead to a total outage
during apiserver upgrades since the checkpointer will aggressively
retire the checkpoint for the deleted apiserver pod before it has
a chance to schedule the new one.

checkpointer: implement state machine.

---

pkg/checkpoint/pod.go
pkg/checkpoint/pod_test.go
pkg/checkpoint/process.go
pkg/checkpoint/process_test.go
pkg/checkpoint/state.go
pkg/checkpoint/state_test.go

checkpointer: make sanitize function idempotent.
The new behavior reads back checkpoints from disk when the checkpointer
restarts, e.g. on node reboot. It was then round-tripping those
checkpoints through the sanitize() function which was not idempotent.
This changes that function to be idempotent.
checkpointer: don't move checkpointer to inactive.
It should move to activeGracePeriod after it is removed. Then it will
clean itself up after the grace period ends.
If it moves to inactive then it will simply get terminated while leaving
garbage around.
cc @thorfour

checkpointer: two fixes (now that checkpointer tests work again)

---

pkg/asset/images.go
pkg/asset/internal/templates.go

Updates checkpointer to e22cc0e3714378de92f45326474874eb602ca0ac.
Also removes `-v=4` from the manifest by default because it's
unnecessarily noisy.

images: update pod-checkpointer.

---

hack/multi-node/user-data.sample
hack/quickstart/kubelet.master
hack/single-node/user-data.sample
pkg/asset/internal/templates.go

As of 1.8 (https://issues.k8s.io/40050) this flag is deprecated and does
nothing.

*/kubelet: remove deprecated flag

---

pkg/asset/internal/templates.go

Wait for Kubernetes v1.8.3 and test that this addresses the warning log in #741. This paves the way to use `ip_vs` in kube-proxy in future, but does not enable it for now.
rel: https://github.com/kubernetes/kubernetes/issues/17470, https://github.com/kubernetes/kubernetes/pull/52003
Closes #741

Add /lib/modules mount to kube-proxy

---

pkg/asset/internal/templates.go

* Disable termination grace period to account for Kubernetes v1.8 changes to DaemonSet behavior that can cause rolls to be slow. See https://github.com/projectcalico/calico/pull/1293
* Fix IPIP mode casing https://github.com/projectcalico/calico/pull/1233

pkg/asset: Disable Calico termination grace period

---

cmd/checkpoint/README.md
pkg/asset/asset.go
pkg/asset/internal/templates.go
pkg/asset/k8s.go

Today, both the checkpointer and kube-proxy re-use the kubelet's credentials to talk to the API server. This means we can't target them with specific RBAC profiles or identify them in audit logs. In addition, when we move to TLS bootstrapping (#663), the kubelet's kubeconfig will no longer hold real credentials.
Switch the checkpointer and kube-proxy to use service account credentials instead of the kubelet's kubeconfig.
Extracted from https://github.com/kubernetes-incubator/bootkube/pull/663 to make that PR smaller. 
cc @dghubble @rphillips

pkg/asset: use service accounts for checkpointer and kube-proxy creds

---

pkg/checkpoint/apiserver.go

This is so we can drop the checkpoint's ClusterRole to a Role. See discussion https://github.com/kubernetes-incubator/bootkube/pull/767#pullrequestreview-76901940

checkpoint: only watch pods in kube-system

---

Makefile

First part to #424 is cross-compiling checkpointer binary in `make all`.

Makefile: Cross-compile checkpointer for multiple archs

---

pkg/asset/internal/templates.go

Supercedes #728 and should remove all critical annotations on the control plane as requested.
Broader discussion and rationale:
* https://github.com/coreos/tectonic-installer/pull/1702
* #728

pkg/assets/internal: Remove critical pod annotations

---

hack/multi-node/bootkube-up
hack/multi-node/user-data.sample

The multi-node worker kubelet wrapper was broken by
929e04f2316876b2fc0f67ccd771dd067dbf1083. This fixes it.

hack: restore multi-node.

---

Makefile

This only compiles a darwin (or whatever) bootkube if you're actually on
darwin and therefore need it for the hack scripts. If you're on linux
then it's just wasted cycles.

Makefile: don't compile darwin by default.

---

cmd/checkpoint/README.md
e2e/checkpointer_test.go
e2e/deleteapi_test.go
e2e/reboot_test.go
e2e/smoke_test.go
glide.lock
glide.yaml
pkg/asset/images.go
pkg/asset/internal/templates.go
vendor/github.com/coreos/ktestutil/testworkload/nginx_workload.go

Instead of extending the existing checkpointer daemonset to run on
worker nodes, start a new checkpointer daemonset instead. This makes
sure that the existing checkpointer (on the apiserver) is not disturbed.
Furthermore, this allows the checkpointer tests to work with the new
checkpointer that is only allowed to look at its own namespace.

e2e: make checkpointer tests more robust.

---

pkg/asset/internal/templates.go

In theory PodCIDR and ServiceCIDR can overlap, letting controller-manager
know service cidr allows it to behave correctly in that case

Pass ServiceCIDR to controller-manager

---

glide.lock
glide.yaml
vendor/github.com/coreos/ktestutil/log-collector/pkg/fluentd/master.go
vendor/github.com/coreos/ktestutil/log-collector/pkg/fluentd/workers.go

bumps ktestutil to pull in the fluentd fixes for timestamps and hostnames.

vendor: bump ktestutil for timestamp fix

---

pkg/asset/internal/templates.go

Make it tiny bit cert rotation friendlier

Make kubecofig-in-cluster use certificate provided by apiserver

---

e2e/checkpointer_test.go
pkg/asset/internal/templates.go

There are no secrets in kubeconfig-in-cluster, so it should be a configmap really

kubeconfig-in-cluster is not a secret

---

hack/quickstart/kubelet.worker

This was forgotten in 929e04f2316876b2fc0f67ccd771dd067dbf1083

quickstart/kubelet.worker: remove deprecated flag

---

pkg/asset/images.go

Calico v2.6.4 contains some bug fixes and a new compatability option `CNI_OLD_CONFIG_NAME` we've been wanting to allow migrations between CNI configs. It basically just means the sidecar can cleanup an old CNI config file on hosts if that variable is set (calico is a damonset). The sidecar already lays down a new CNI config on each host as part of startup. This allows migrations and unblocks #711
https://github.com/projectcalico/calico/releases/tag/v2.6.4

pkg/asset: Update Calico from v2.6.3 to v2.6.4

---

pkg/asset/images.go

Meant to include this with #818, we bump the calico and sidecar image together.

pkg/asset: Update calico/cni to v1.11.2

---

cmd/checkpoint/main.go
pkg/checkpoint/checkpoint.go
pkg/checkpoint/state_test.go

This allows users to configure the checkpoint removal grace period
parameter as a flag. This may be useful for tests, among other things.

checkpointer: make grace period a flag.

---

pkg/checkpoint/checkpoint.go
pkg/checkpoint/config_map.go
pkg/checkpoint/manifest.go
pkg/checkpoint/pod.go
pkg/checkpoint/pod_test.go
pkg/checkpoint/secret.go

This reads the uid from the security context and uses it when
checkpointing secrets and configmaps.
If there is a conflict between containers or the outer pod security it
returns an error for now. In the future we could make multiple copies,
one with each uid.

checkpointer: write secrets and configmaps with uid.

---

e2e/checkpointer_test.go
pkg/asset/images.go
pkg/asset/internal/templates.go

Also use new flag (in this checkpointer version) to vastly shorten the
grace period in the checkpoint tests.

checkpointer: bump default checkpointer version.

---

Documentation/network-requirements.md
cmd/bootkube/render.go
e2e/checkpointer_test.go
hack/multi-node/bootkube-up
hack/quickstart/init-master.sh
hack/quickstart/quickstart-aws.md
hack/quickstart/quickstart-gce.md
hack/single-node/bootkube-up
hack/tests/conformance-gce.sh
pkg/asset/images.go
pkg/asset/internal/templates.go
pkg/recovery/recover_test.go

Changes the apiserver defaults to listen on port 6443 and use a non-root
user. The port matches the upstream default and reflects best practices.
Production users can put the apiserver behind a load-balancer to forward
443 to 6443.

apiserver: run as non-root user.

---

pkg/asset/internal/templates.go

Update admission controllers from https://kubernetes.io/docs/admin/admission-controllers/#podnodeselector. Blocked by: #810

pkg/asset: apiserver: Update the recommended set of admission controllers for 1.9

---

Makefile

The `-i` flag caches builds in $GOPATH/pkg. Speeds this up
considerably when rebuilding bootkube a lot of times.

Makefile: default GOFLAGS to enable build caching

---

e2e/checkpointer_test.go

Unable to determine root cause. Disabling the test now to cut down on friction for other PRs. For now, fixes #816.

e2e: remove flaky checkpointer test

---

hack/quickstart/init-node.sh
hack/terraform-quickstart/start-cluster.sh

This prevents users from incorrectly being instructed to use the `kubeconfig-kubelet` file to authenticate to the cluster. That is no longer appropriate with TLS bootstrapping, and there is a plain `kubeconfig` file that should be used instead.

hack: rearrange log messages, use correct kubeconfig

---

hack/tests/conformance-gce.sh
hack/tests/conformance-test.sh

Conformance tests for Kubernetes 1.9 need to be run with Go v1.9.
```
[710876.901729] golang[6]: [  607.394616] golang[6]: Detected go version: go version go1.8.4 linux/amd64.
[710876.902320] golang[6]: [  607.395062] golang[6]: Kubernetes requires go1.9.1 or greater.
[710876.902548] golang[6]: [  607.395288] golang[6]: Please install go1.9.1 or later.
[710876.904858] golang[6]: [  607.398040] golang[6]: !!! [0118 12:07:34] Call tree:
[710876.906480] golang[6]: [  607.399712] golang[6]: !!! [0118 12:07:34]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)
```
Triggered in bootkube-dev job 68.

hack: Update conformance tests to use Go 1.9.2

---

Makefile

Reverts kubernetes-incubator/bootkube#838
`-i` will attempt to `go install os/user` and `go install net` into the GOROOT (/usr/lib/golang/pkg/linux_amd64) requiring root privileges to run make within the project root. Preserving the golang build to not require root is preferable.

Revert "Makefile: default GOFLAGS to enable build caching"

---

pkg/asset/images.go

Minor bug fixes:
https://github.com/projectcalico/calico/releases/tag/v2.6.6
https://github.com/projectcalico/calico/releases/tag/v2.6.5

pkg/asset: Update Calico from 2.6.4 to 2.6.6

---

.gitignore

Ignore more artifacts of running e2e/hack scripts.
Hopefully this will prevent me from `git add -A`-ing and pushing a bunch of random log files and binaries into Git and/or an open PR.

gitignore: ignore hack/e2e litter

---

pkg/asset/images.go
pkg/asset/internal/templates.go

* Update kube-dns from v1.14.5 to v1.14.8
* Switch kube-dns sidecar to probe for SRV records (recommended for 1.9)
* https://github.com/kubernetes/kubernetes/pull/51378

Update kube-dns and switch sidecar to probe SRV records

---

Makefile
e2e/reboot_test.go

The current Makefile doesn't fail builds on `gofmt` errors. This changes causes it to fail.

Fail release build on gofmt diffs

---

pkg/asset/internal/templates.go

kube-{flannel,proxy} need to run on every node, no matter what
the taints is. Without kube-{flannel,proxy} the node is never
ready.
I'm not sure if the node will work without calico-node, but it should
run on every node anyway.
Fix #699

pkg/asset: kube-{flannel,proxy}, calico-node: Tolerate all taints

---

Makefile

make is using `sh` on Jenkins by default. This tweak sets the shell to bash to fix the following error on `make check`:
```
05:22:18 [1650506.967906] golang[6]: /bin/sh: 1: read: arg count
05:22:18 [1650507.054205] golang[6]: /bin/sh: 1: [: 2: unexpected operator
```

use bash for the makefile shell

---

.travis.yml
Makefile
hack/terraform-quickstart/main.tf

fails `make check` if terraform files are not formatted correctly.

add terraform fmt validation

---

pkg/asset/internal/templates.go

In Kubernetes 1.9, we should be using `apps/v1` for Deployments and DaemonSets. https://kubernetes.io/docs/reference/workloads-18-19/

Switch Deployments and DaemonSets to apps/v1

---

pkg/asset/asset.go

os.Mkdir will error on an existing directory. Allows for existing mount points for assets.
Fixes #884

assets: use MkdirAll to not error on existing dir

---

pkg/asset/internal/templates.go

* PersistentVolumeLabel admission controller is deprecated in 1.9
I noticed warnings in apiserver logs that this admission controller is deprecated. It is indeed mentioned in 1.9 release deprecation [notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md#deprecations) and details are found in [#52618](https://github.com/kubernetes/kubernetes/pull/52618).

Remove PersistentVolumeLabel admission controller flag

---

e2e/deleteapi_test.go

The control plane can take in excess of 60 seconds to be restored. In my testing, I have seen the control plane take anywhere from 40 seconds to 1 minute 40 seconds to be fully functional again. The TestDeleteAPI test simply ignores the restoration of the control plane and continues without verifying the control plane so the next unit test can run.

wait for the controlPlane to be restored

---

pkg/asset/internal/templates.go

When nodes reboot, such as in the TestReboot e2e test case, it can take
a while for the cluster to get stable due to the dependency chain
between the apiserver, flannel, and the controller manager and so on.
If the controller manager was in the middle of doing something (e.g.
rolling the apiserver) while a reboot occurs, we need to ensure that the
controller manager gets healthy again. This requires keeping the
checkpointed apiserver up.
The downside is that this may run pods considerably longer than they
ought to. However, this is a failure recovery scenario, and running an
old pod is not a huge violation of k8s semantics (daemonsets strive for
1-at-a-time semantics but don't guarantee it).
This should alleviate the flakes observed in #824.

checkpointer: add 5m grace period flag.

---

pkg/bootkube/bootkube.go
pkg/bootkube/create.go
pkg/bootkube/status.go

Am removing some kubectl code and this is a good cleanup that can go in on its own.

pkg/bootkube: remove global variable

---

pkg/asset/internal/templates.go

Can use v1 now that we're on Kubernetes 1.9

pkg/asset: Switch apiVersion to rbac.authorization.k8s.io/v1

---

pkg/recovery/recover.go
pkg/recovery/recover_test.go

Fixes: https://github.com/kubernetes-incubator/bootkube/issues/902
Adds hostNetwork: true to all generated assets and tests for same.

bootkube/pkg/recovery/recover fix hostNetwork

---

hack/jenkins/README.md
hack/jenkins/images/bootkube-e2e/Dockerfile
hack/jenkins/jobs/bootkube_e2e.groovy
hack/jenkins/pipelines/bootkube-e2e/Jenkinsfile
hack/jenkins/scripts/e2e.sh
hack/jenkins/scripts/tqs-down.sh
hack/jenkins/scripts/tqs-up.sh
hack/quickstart/init-master.sh
hack/terraform-quickstart/main.tf
hack/terraform-quickstart/variables.tf

Adds a new tree `hack/jenkins` to the tree:
```
hack/jenkins
├── images
│   └── bootkube-e2e
│       └── Dockerfile
├── jobs
│   └── bootkube_e2e.groovy
├── pipelines
│   └── bootkube-e2e
│       └── Jenkinsfile
└── scripts
├── e2e.sh
├── tqs-down.sh
└── tqs-up.sh
```
This holds the majority of the configuration for all bootkube jobs. (Somethings are captured in our Jenkins configuration repo, instead of here, because they are "global" settings. With rare exception, all job-specific config is and belongs here.)
The jobs added here, `bootkube-e2e-{calico,flannel}` will execute on Kubernetes agents. This was chosen to minimize the amount of special care needed on the hosts. Even for a fairly self-contained project like `bootkube`, there is value in having a container with known-good …

jenkins: add initial bootkube-e2e jobs

---

Documentation/development.md
hack/jenkins/README.md

Update:
* `Documentation/development.md` - mention the commands for new jobs
* `hack/jenkins/README.md` - correct bootkube-e2e-* job descriptions

jenkins: update development readme with trigger information

---

cmd/bootkube/main.go

* Use SilenceErrors to suppress the double printing of errors
Fixes #910

error: SilenceErrors and tweak error output

---

hack/jenkins/jobs/bootkube_e2e.groovy

This is just a bit of additional flexibility, but this will enable privileged users to queue jobs with their own repositories, so they can test before sending PRs.
Demo, for those that have access: https://jenkins-kube-upstream.prod.coreos.systems/job/tku-bootkube-e2e-calico/parambuild?sha1=origin/psp&repo_url=https%3A%2F%2Fgithub.com%2Fericchiang%2Fbootkube.git

jenkins: allow user to override repo_url

---

hack/jenkins/jobs/bootkube_e2e.groovy
hack/jenkins/pipelines/bootkube-e2e/Jenkinsfile
hack/jenkins/scripts/gather-logs.sh
hack/jenkins/scripts/tqs-down.sh
hack/jenkins/scripts/tqs-up.sh

jenkins: bootkube-e2e: collect, archive logs:
* Collects systemd+docker logs from the machines, as the existing Jenkins was doing.
* Archives all artifacts at the end, making them easily accessible from the job UI
jenkins: bootkube-e2e: upload logs to s3:
* Tees into log files in each stage (Jenkins makes it impossible to get the raw build log in a declarative pipeline from scm job, this was the best option I could come up with)
* Makes a `tar.gz` of all archived assets.
* Uploads the archived assets, and the `tar.gz` (convenience) in a public s3 bucket
* Sets the commit status to point to the public s3 bucket instead of to our private Jenkins

Jenkins: Collect e2e logs & archive in public S3 bucket

---

hack/jenkins/jobs/bootkube_e2e.groovy

I was hoping to "late" interpolate the repo name in, but it's unnecessary for allowing users to run jobs on un-pushed PRs, /and/ it breaks GHPRB.
So, interpolate it when Job DSL runs and creates the job, instead of allowing the placeholder to flow into the job.
cc: @rithujohn191

jenkins: bootkube-e2e: groovy interpolate repo name at job creation time

---

hack/jenkins/pipelines/bootkube-e2e/Jenkinsfile

Just noticed a tiny bit of resource leakage in Jenkins (https://jenkins-kube-upstream.prod.coreos.systems/job/tku-bootkube-e2e-flannel/78/console). This should prevent that.
cc: @rithujohn191 @rphillips

jenkins: prevent resource leak when log agg fails

---

README.md
pkg/bootkube/create.go

Fixes #926 and documents the change as requested.
cc: @aaronlevy @ericchiang 
I don't have an opinion on this:
* Pro: there is unlikely any valid (non-contrived) scenario where a user would want to not have NSs created fist
* Con: users may think that all dependencies can/should be automatically determined, it makes the process less simple and special cases certain resources

pkg/bootkube: create namespaces before other resources

---

pkg/asset/images.go

Closes https://github.com/kubernetes-incubator/bootkube/issues/934
cc @colemickens 
**Upgrade note:** Users MUST update their checkpointer before updating to Kubernetes v1.10

pkg/asset: update checkpointer to include CRI v1alpha2 support

---

pkg/asset/internal/templates.go

There is a typo in the RBAC manifest for calico after the update to version 3 for `clusterinformations`.

pkg/assets: calico 3.0 rbac typo

---

Documentation/root-requirements.md

Documentation/root-requirements: API server no longer needs root

---

Makefile

This [became the default behavior in Go 1.6 and the switch was dropped in Go 1.7][1].  We've required Go 1.8+ since at least #775, so there's no need to set the switch anymore.
[1]: https://blog.golang.org/go1.7

Makefile: Drop GO15VENDOREXPERIMENT

---

build/git-version.sh

Simplify the logic from #47 to:
* Move from Bash to a generic POSIX shell.  This makes the script more portable (it will work on POSIX systems without Bash).  It does mean we need to drop the `set` (which [is not in POSIX][1]), but that's not a major problem because:
* We can use `&&`-chaining instead of `set -e`.
* We do only have the one locally-defined variable, so we don't need `set -u`.
* The simpler logic has no pipes, so `set -o pipefail` would no longer matter.
* Replace the previous multiple Git calls with a single call to `git describe`.
* Use `--dirty` so we can drop the previous `diff` call.
* Drop `--tags`, because we don't want to use lightweight (non-annotated) tags.  We want to use annotated tags, because we want to use signed release tags.  There's no code check for tag …

build/git-version: Only call 'git' once

---

Documentation/development.md
Makefile

`GOBIN` (documented [here][1]) defaults to `DIR/bin`, but it's a configurable variable in its own right.  This command updates our calculations, using `?=` (documented [here][2]) to avoid expensive shell operations when we don't actually need the result (because a different target was called or because the user provided their own value).
I've also used `go env GOPATH` to get the ([platform-specific][1]) default value when the environment variable is not set.
And I've used [`cut`][3] instead of [`awk`][4] to pull out the first component of `GOPATH`.  Both are in POSIX, but `cut` is a simpler tool for this particular problem.
This will have trivial context conflicts with the in-flight #948.  I'm happy to rebase the other if/when one of them lands.
[1]: …

Makefile: Respect GOBIN

---

Makefile

This was my intention with #949, but I seem to have missed the actual code :/.  Instead, that pull-request landed an earlier implementation which we intended to drop based on #949 [review][1].
This commit has the intended implementation.  For detailed motivation, see the description in dbf0b6a5.
[1]: https://github.com/kubernetes-incubator/bootkube/pull/949#issuecomment-378292372

Makefile: Actually use 'go install ...' for the install target

---

hack/jenkins/pipelines/bootkube-e2e/Jenkinsfile
hack/jenkins/pipelines/hyperkube-release/Jenkinsfile

Jenkins is currently marking stages with failing scripts as "succeeded". It looks like this is happening because of our piping into `tee`.
Replace `sh` with a new, custom `bash` step that will `set -euo pipefail` initially to safely run scripts and surface failures correctly.

Replace Jenkins `sh` with a `bash` step that sets `set -euo pipefail`

---

hack/multi-node/user-data.sample
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/single-node/user-data.sample
pkg/asset/images.go

gcr.io/google_containers is being deprecated in favor of the k8s.gcr.io domain.

use k8s.gcr.io mirror

---

pkg/asset/internal/templates.go

As of kubernetes 1.10 `--admission-control` has been deprecated in favor of `--enable-admission-plugins`
This new flag is already in place for the bootstrap rendered manifest
https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/internal/templates.go#L227
This PR also sets that flag for the apiserver template
Note: trying 1.9 clusters won't work using the new flag, this could be fixed doing just the opposite, replacing the new flag at the rendered bootstrap manifest with the old one, since it is still working. I'd stick to the new flag, and let 1.9 users modify the rendered manifests if using bootkube > 0.12.0

Remove deprecated admission plugin flag

---

pkg/asset/images.go

* https://github.com/kubernetes/kubernetes/pull/61908

Update kube-dns from v1.14.8 to v1.14.9

---

pkg/asset/internal/templates.go

Changing this to `Default` policy was originally to support cloud-providers. However, we can now allow it to use both the cluster and host DNS.

pkg/asset/internal: allow controller-manager to use cluster+host DNS

---

Makefile

I'm reverting #870 here and also removing the code that seemed to have motivated it.  Details on the individual changes in the commit messages.  The `find` commit is something of a drive-by; I'm happy to split it out into its own pull request if that would make review easier.

Makefile: Drop hard-coded Bash and simplify gofmt

---

.travis.yml
Documentation/development.md
Makefile

The `clean` target has been included there since 1f346000 (#46).  But `clean` has been a `release` prerequisite since 04848d13 (#47), so the `.travis.yml` entry is redundant.

Makefile: Remove clean prerequisites from build targets

---

.travis.yml
Makefile
build/build-release.sh
cmd/checkpoint/README.md
hack/tests/conformance-gce.sh
hack/tests/conformance-test.sh
pkg/checkpoint/pod.go
pkg/tlsutil/tlsutil.go

Kubernetes 1.12.x introduced new logic for Affinity [1]. In addition to
new logic, the Pod contains a default affinity. The new default affinity
gets serialized into the checkpoint file, and the 1.12.x kubelet does
not restore the pod due to the affinity.
This PR removes the affinity from the spec and documents that affinity's
are not supported.
```
"affinity": {
"nodeAffinity": {
"requiredDuringSchedulingIgnoredDuringExecution": {
"nodeSelectorTerms": [
{
"matchExpressions": null
}
]
}
}
},
```
[1] https://github.com/kubernetes/kubernetes/pull/68173
[2] https://github.com/kubernetes/kubernetes/blob/e39b510726113581c6f6a9c2db1753d794aa9cce/pkg/controller/daemon/util/daemonset_util.go#L183-L196

checkpointer: ignore Affinity within podspec

---

cmd/bootkube/start.go
pkg/bootkube/bootkube.go
pkg/bootkube/status.go

By default we wait for the pods pod-checkpointer, kube-apiserver, kube-scheduler, kube-controller-manager in the kube-system namespace. This PR adds the `--required-pods` flag to the start command to customize this list, including custom namespaces of the shape `<ns>/<pod-name>`.

start: add --require-pods flag

---

pkg/checkpoint/checkpoint.go
pkg/checkpoint/kubelet.go

Change pod-checkpointer to first try to list pods via the Kubeletsecure (10250) endpoint, then fallback to the Kubelet read-only (10255) endpoint, before defaulting to an empty list of parent pods
Related: #1025

pkg/checkpoint: Try kubelet secureClient, fallback to read-only

---

hack/multi-node/README.md

Remove prefixed `$` and make the instructions to run e2e test copy and
pastable.

Make e2e test commands copy-pastable

---

pkg/recovery/apiserver.go
pkg/recovery/recover.go
pkg/recovery/recover_test.go

This bug fixes #977
My knowledge of kubernetes client-go is almost non, however because the recovery is failing on old resource types I have shifted these to use apps/v1 https://godoc.org/k8s.io/client-go/kubernetes#Clientset.AppsV1 which should be backwards compatible with the extensionsv1 interface.
Please let me know if I am missing something or am tackling this from a wrong perspective.

Handle AppsV1 resources inside bootkube recover

---

pkg/checkpoint/manifest.go
pkg/checkpoint/pod.go

Due to changes in Kubernetes 1.16, the node-role.kubernetes.io label can
no longer be automatically applied by the kubelet. Due to this, we had
to remove it from the `--node-labels` flag. This caused the static
pod-checkpointer to fail to run after a complete loss of the control
plane (e.g. all control plane nodes rebooted) because it had a
`nodeSelector` inherited from the `DaemonSet` that used the
`node-role.kubernetes.io` label. This PR adds logic to strip off all
`node-role.kubernetes.io` related metadata from the static manifest, which
allows the scheduling to occur.

fix: remove node selector from static manifests

---

hack/multi-node/bootkube-up
hack/multi-node/user-data.sample
hack/single-node/bootkube-up
hack/single-node/user-data.sample
pkg/asset/asset.go
pkg/asset/internal/templates.go
pkg/asset/k8s.go
pkg/asset/tls.go

* Changes api-server cert org to system:masters
* This allows the api-server to maintain admin access and also ensure that kubectl logs/exec etc remain functional 
* Changes to `hack/*` to move the kubelet from `AllwaysAllow` to `WebHook`authn mode
* Fixes broken `sed` command.

Enables Kubelet Auth

---

pkg/asset/asset.go
pkg/asset/internal/templates.go
pkg/asset/k8s.go

* Adds manifests for checkpointer cluster role and cluster role binding which is required by the secure client. 
to be merged after #1069

adds rbac for checkpointer secure client

---

pkg/asset/images.go
pkg/asset/internal/templates.go

- Adds Pod Anti Affinity
- Updates replicas to 2
- Adds lameduck plugin to health ( it allows 5 seconds wait time after its unhealthy to shutdown )
- Fixes Labels kube-dns to coredns
- Adds Readiness Probe
- Updates CoreDNS to 1.6.5

CoreDNS Updates

---

cmd/bootkube/render.go
pkg/asset/asset.go
pkg/asset/internal/templates.go
pkg/asset/k8s.go

This PR adds a ClusterName value to the bootkube config struct, an
optional flag to bootkube render,  as well
as using any specified value to create a context name in the kubeconfig file.
This allows tools like [kconf](https://github.com/particledecay/kconf) to merge various bootkube-created
kubeconfigs
Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>

feat: add cluster name to configs and create context name

---

OWNERS

Hey folks, for my own clusters, I no longer use bootkube and haven't for a while. Its been a good few years, but I think its best I take myself off the list and leave it in the capable hands of those who are actively using it.

Remove dghubble from OWNERS list

---

cmd/bootkube/render.go
pkg/asset/asset.go
pkg/asset/asset_test.go
pkg/asset/internal/templates.go

Adds dual stack (IPv4 + IPv6) support for:
- Service subnets
- Pod subnets
- API service
- DNS service
Ref issue #1079
Signed-off-by: Seán C McCord <ulexus@gmail.com>

Add support for multiple Pod and Service subnets

---

pkg/bootkube/status.go

This introduces support for waiting for all nodes to report back as Ready.
This fixes an edge case where self hosted pods come up on other control
plane nodes but not on the bootstrap node and all control plane nodes are
pointed to the bootstrap node.
Depends on #1087.

feat: add support for watching node status

---

pkg/bootkube/create.go

Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

pkg/bootkube: fix no newline in output while waiting for the CRDs
