CONTRIBUTING.md
DCO
LICENSE
NOTICE

Add CoreOS project documents

---

pkg/assets/assets.go
pkg/assets/templates/kube-apiserver.yaml
pkg/assets/templates/kubelet.json
pkg/assets/templates_gen.go

Add kubelet template

---

README.md

/cc @philips @derekparker @pbx0

Add hack dirs to readme and some additional details

---

Makefile
README.md
hack/multi-node/Vagrantfile
hack/multi-node/conformance-test.sh
hack/single-node/conformance-test.sh
hack/tests/conformance-test.sh

Run conformance tests against the hack/single-node and hack/multi-node installs:
`make conformance-single`
`make conformance-multi`

Hack build conformance tests

---

.gitignore
.travis.yml
Makefile
build/build-release.sh
build/git-version.sh
cmd/bootkube/main.go
pkg/version/version.go

/cc @derekparker @pbx0 @dghubble

Add release build process

---

cmd/checkpoint/main.go

Adds a check to ensure the API is actually running, responding to
requests, when the checkpoint service notices the pod manifest. Came
accross an issue when upgrading a cluster where the API server daemonset
was removed, and the API server brought down, but the kubelet still
returned that pod from its read-only API. This meant that the checkpointer
never enabled the temp apiserver static manifest, meaning the
upgrade could not continue.
Now, if we notice that an API server pod is returned from kubelet (the
actual, self-hosted one, not a temp one) then we also check that it is
up and accepting requests, otherwise we assume it to be dead.

cmd/checkpoint: Verify API server running

---

README.md
hack/quickstart/README.md
hack/quickstart/init-worker.sh
hack/quickstart/quickstart-aws.md
hack/quickstart/quickstart-gce.md

Adds an AWS quickstart guide, and makes some minor updates to the README/GCE guides.
fixes https://github.com/coreos/bootkube/issues/32
/cc @philips

Update quickstart guides

---

hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker

This should fix -- https://github.com/coreos/bootkube/issues/99 (but don't want github to auto-close issue until confirmed)

quickstart: Mount host resolv.conf into kubelet container

---

hack/tests/conformance-test.sh

I'll post some results if/when they pass.

hack/tests: Fix conformance version separator

---

hack/multi-node/bootkube-up
hack/single-node/bootkube-up
pkg/bootkube/bootkube.go
pkg/bootkube/create.go
pkg/bootkube/status.go

Will output any errors on exit and output all pod statuses if any have changed.
/cc @pbx0

Be more verbose with stdout logs

---

pkg/bootkube/create.go

Bootkube will fail when its not able to successfully create assets for any other reason that "already exists error". 
Seems that bootkube is not failing when an error, such as incorrect yaml occurs. 
Fixes #131

Make bootkube fail when not successfully creating assets.

---

pkg/bootkube/create.go

fixes https://github.com/kubernetes-incubator/bootkube/issues/131
/cc @kenan435 RE: https://github.com/kubernetes-incubator/bootkube/issues/131#issuecomment-248047201

Log on asset creation error - do not exit

---

cmd/checkpoint/main.go

cmd/checkpoint: remove break statement from secret checkpoint loop

---

Documentation/upgrading.md

Documentation: Add on-host kubelet upgrade

---

pkg/util/etcdutil/migrate.go

I'm getting error like "need to use GroupVersion to create RESTClient".
I don't really need to create rest client indeed. I can get that from clientset CoreClient.

create 1.4 clientset from config and use its RESTClient

---

cmd/bootkube/render.go
pkg/asset/asset.go
pkg/asset/k8s.go

render: add flag to optionally create self hosted assets

---

hack/multi-node/bootkube-up
hack/single-node/bootkube-up

As much as I love awk this is totally unnecessary. Just use `ssh -F`
instead.

hack: multi-node use the ssh-config

---

pkg/asset/internal/templates.go

fixes https://github.com/kubernetes-incubator/bootkube/issues/194
/cc @hongchaodeng @xiang90

Set proxy hostname and cluster cidr

---

cmd/checkpoint/main.go

Make run func generic. Preparing for adding etcd checkpoint support.

checkpoint: make run func generic

---

pkg/asset/internal/templates.go

The dnsmasq sidecar to expose metrics was [recently released](https://github.com/kubernetes/contrib/pull/1871#issuecomment-258540158). Skydns (within `kube-dns`) by default exposes Prometheus metrics on a random port, and this defines it to be `8083`.
It would be nice to expose those metrics by default, without having to modify the deployment after deploying a new cluster.

expose skydns and dnsmasq metrics

---

RELEASING.md

Add initial release documentation

---

cmd/checkpoint/main.go

/cc @aaronlevy @derekparker 
This is based on my offline discussion with @aaronlevy. Kubelet will add -xxx as a suffix to the checkpoint pod it starts, so we do not need to have the special name.

checkpoint: remove template checkpoint pod spec

---

cmd/checkpoint/main.go

@aaronlevy 
Now we load the existing manifests, and only try to install the manifest if checkpoint exists. The previously logic try to create static pod blindly. 
Last change for the preparation of the final code logic restructure. With the disk manifest preloading, the checkpointer knows exactly what it expects to recreate if not exists.

checkpoint: explicitly load checkpoint manifests

---

cmd/checkpoint/main.go

checkpointer: log to stderr

---

cmd/checkpoint/main.go

We only got part way to where we wanted to be - and likely implementing this differently anyway. I was going to revert this for now so that we can layer some simple fixes on top (like logging and the name change). If we need to we can come back and revert the revert.
/cc @xiang90

Checkpoint revert

---

hack/tests/conformance-gce.sh

Fixed name keeps CI from running tests in parallel

tests: parameterize prefix for GCE assets in conformance tests

---

pkg/asset/internal/templates.go

Bump to new checkpointer implemented in https://github.com/kubernetes-incubator/bootkube/pull/238

checkpointer: bump to new implementation

---

Makefile
README.md

Added make target that combines building, resetting the VM, and
provisioning it with bootkube to make iterating faster.
Installs Go archives to speed up builds.

Run make target

---

CONTRIBUTING.md
LICENSE
OWNERS
code-of-conduct.md

Kubernetes provides some project template documents here:
https://github.com/kubernetes/kubernetes-template-project
This PR harmonizes the "housekeeping" files

Use official kubernetes documents

---

hack/quickstart/quickstart-gce.md

fixes typo: illegal space

---

cmd/checkpoint/main.go
cmd/checkpoint/main_test.go
image/checkpoint/checkpoint-pod.yaml

Fixes https://github.com/kubernetes-incubator/bootkube/issues/267
/cc @Quentin-M

checkpoint: Get local pod running state from /runningpods/ endpoint

---

hack/tests/conformance-gce.sh

Getting intermittent "Too many authentication failures" when launching GCE nodes. This seems to help and is a stop-gap until can dig into why this is occurring.
/cc @Quentin-M

hack/tests: add logging and a delay when launching GCE workers

---

hack/multi-node/Vagrantfile
hack/multi-node/bootkube-up

Separated from #259.
We have tested it.

hack/multi-node: self hosted etcd option

---

cmd/checkpoint/main.go

checkpoint: re-use http client transport

---

Makefile
pkg/asset/internal/templates.go
pkg/util/etcdutil/migrate.go
vendor/github.com/coreos/etcd-operator/pkg/spec/backup.go
vendor/github.com/coreos/etcd-operator/pkg/spec/cluster.go
vendor/github.com/coreos/etcd-operator/pkg/spec/etcd_cluster_list.go
vendor/github.com/coreos/etcd-operator/pkg/spec/self_hosted.go

See https://github.com/coreos/etcd-operator/issues/594#issuecomment-270475704

fix: self hosted etcd

---

pkg/util/etcdutil/migrate.go
pkg/util/etcdutil/start_etcd.go

	 SHE: remove boot etcd manifest after migration

---

hack/multi-node/bootkube-up
hack/single-node/bootkube-up

Increases the glog verbosity of the bootstrap components by using an
environment variable.
Closes #198 by making verbose logging default.

Verbose glog level for bootstrap components

---

pkg/asset/internal/templates.go
pkg/util/etcdutil/migrate.go
pkg/util/etcdutil/start_etcd.go

- etcd operator: beta release v0.2.0
- etcd: v3.1.0

self hosted etcd: bump version

---

pkg/bootkube/bootkube.go
pkg/bootkube/parse.go

pkg/bootkube: use full asset path in log messages

---

Makefile
pkg/asset/internal/templates.go
pkg/util/etcdutil/migrate.go
pkg/util/etcdutil/start_etcd.go
vendor/github.com/coreos/etcd-operator/pkg/spec/backup.go
vendor/github.com/coreos/etcd-operator/pkg/spec/cluster.go
vendor/github.com/coreos/etcd-operator/pkg/spec/etcd_cluster_list.go

This PR updates etcd operator spec to beta and updates SHE code path for it.

SelfHostedEtcd: updates to use beta of etcd operator

---

README.md

Adding the slack channel for user support

adds k8s slack channel info to readme

---

cmd/checkpoint/main.go

Use the client certs in the kubelet's kubeconfig to talk to the
kubelet API. This has no effect currently, but will once the
kubelet enables API auth. We assume the kubelet's client certs
originate from the same CA that cert auth trusts.
These are checkpointer changes split out from #345 so we can
do a release then import it later once we turn on kubelet auth.
cc @pbx0

cmd/checkpoint: use kubelet's client certs for the kubelet API

---

hack/multi-node/Vagrantfile
hack/multi-node/bootkube-up
hack/multi-node/user-data.sample
hack/single-node/Vagrantfile
hack/single-node/bootkube-up
hack/single-node/user-data.sample

fixes https://github.com/kubernetes-incubator/bootkube/issues/362
cc @carolynvs @ericchiang

hack: copy ca.crt to host as part of vagrant provisioning

---

hack/multi-node/Vagrantfile
hack/single-node/Vagrantfile

hack: ensure /etc/kubernetes dir exists

---

pkg/asset/internal/templates.go
pkg/util/etcdutil/start_etcd.go

1. get rid of `sh`
2. fix `flock` command

*: fix etcd and kenc container command

---

hack/single-node/bootkube-up
pkg/util/etcdutil/start_etcd.go

Add single-node support to address https://github.com/kubernetes-incubator/bootkube/issues/337

Single node self hosted etcd

---

pkg/asset/internal/templates.go

Add liveness probes

---

Makefile
hack/multi-node/user-data.sample
hack/single-node/user-data.sample
hack/tests/conformance-test.sh
pkg/asset/internal/templates.go
vendor/k8s.io/kubernetes/pkg/version/base.go
vendor/k8s.io/kubernetes/plugin/pkg/admission/security/podsecuritypolicy/admission.go
vendor/k8s.io/kubernetes/plugin/pkg/admission/security/podsecuritypolicy/admission_test.go

Cherry pick of version bump from master

Bump k8s version v1.5.5

---

pkg/asset/internal/templates.go

No functional change. Just cleaning up for easier maintenance.

pkg: Alphabetize hyperkube command options

---

RELEASING.md

Update the name of the jenkins job for the conformance test.

RELEASING.md: Update the jenkins job name.

---

pkg/asset/internal/templates.go

The recommended set is sepecified here:
https://kubernetes.io/docs/admin/admission-controllers/#is-there-a-recommended-set-of-plug-ins-to-use
Fixes #438.

Update APIServer admission controllers.

---

pkg/asset/asset.go
pkg/asset/internal/templates.go

Rename kenc to kube-etcd-network-checkpointer.

---

cmd/checkpoint/main.go
cmd/checkpoint/main_test.go

This is a copy of https://github.com/kubernetes-incubator/bootkube/pull/387 with the conflicts resolved and bumped for v1.6 object types
fixes https://github.com/kubernetes-incubator/bootkube/issues/378

Ensure labels are preserved

---

cmd/checkpoint/main.go
cmd/checkpoint/main_test.go

Another step towards un-vendoring Kubernetes.

Switch checkpointer to use client-go.

---

pkg/bootkube/bootkube.go

glide.yaml is not touched until another etcd denpendency is fixed.

pkg/bootkube: Remove dependency on github.com/coreos/etcd/pkg/fileutil.

---

pkg/util/etcdutil/migrate.go

After running into issues deploying self-hosted etcd on Tectonic, I saw
lots of error logs. I thought the logs could be improved and be more
consistent.
cc @hongchaodeng

pkg/util/etcdutil: improve etcd migration logs

---

hack/multi-node/user-data.sample
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/single-node/user-data.sample

Alphabetize options for easier maintenance. No functional changes.

hack: Alphabetize kubelet options in hack scripts

---

.gitignore
cmd/bootkube/render.go
pkg/asset/asset.go
pkg/asset/internal/templates.go
pkg/asset/k8s.go

I just specified the values in a constant for now, but we can do
something more sophisticated if we want.

Extract all image versions from templates.

---

README.md
cmd/bootkube/recover.go
pkg/recovery/apiserver.go
pkg/recovery/recover.go
pkg/recovery/recover_test.go

Also fix some path munging that I somehow broke in the process of
writing tests :-/

Add apiserver recovery backend.

---

Documentation/network-requirements.md

Fixes #344. Wasn't too sure about all of them, so documented the ones I knew about. Feel free to add any extras I left out and I'll update the doc.

Add port requirements doc

---

hack/quickstart/init-node.sh
hack/quickstart/init-worker.sh
hack/quickstart/quickstart-aws.md
hack/quickstart/quickstart-gce.md
hack/terraform-quickstart/main.tf
hack/terraform-quickstart/outputs.tf
hack/terraform-quickstart/start-cluster.sh
hack/terraform-quickstart/variables.tf
hack/tests/conformance-gce.sh

This is a requirement for the etcd-scaling test to be run against a terraform-quickstart created cluster.
cc @aaronlevy @yifan-gu

support bringing up more masters in terraform and quickstart scripts

---

Makefile
e2e/README.md
e2e/main_test.go
e2e/smoke_test.go

start of e2e tests

---

pkg/asset/asset.go
pkg/asset/k8s.go

/cc @diegs 
This makes it easier to load in recovery etcd template and output recovery etcd manifest as a static pod.

asset: make it easier to load and write asset out of rendering phase

---

cmd/bootkube/render.go
pkg/asset/images.go

/cc @diegs 
for https://github.com/kubernetes-incubator/bootkube/pull/528#discussion_r117382216

*: move image assignment to asset

---

pkg/util/etcdutil/migrate.go
pkg/util/etcdutil/util.go

/cc @diegs 
we want to reuse the cluster wait logic for recovery.

etcdutil: factor out wait ready

---

e2e/deleteapi_test.go
e2e/etcdscale_test.go
hack/terraform-quickstart/iam.tf
hack/terraform-quickstart/main.tf

Also adds a work-around for hashicorp/terraform#1885

e2e: add delete apiserver test

---

cmd/checkpoint/main.go

This now checks if the file exists, and if so if the content is actually
different from what we are about to write.
Fixes #544

Only write active checkpoints when changed.

---

pkg/asset/internal/templates.go

pkg/asset/internal: Set rolling update strategy for DaemonSets

---

pkg/asset/images.go

pkg/asset: Bump checkpointer version

---

README.md
cmd/bootkube/recover.go
hack/multi-node/bootkube-test-recovery-self-hosted-etcd
pkg/recovery/etcd.go
pkg/recovery/etcd_template.go
pkg/recovery/recover.go
pkg/recovery/recover_test.go
pkg/util/etcdutil/migrate.go
pkg/util/etcdutil/util.go

/cc @diegs 
This is still WIP. But if you want to take a early view. Do it :P. I will keep this updated with my progress, and ping you again when it is finished and tested.

*: add backup file option to recover subcommand

---

e2e/node.go

Fix GetCluster() and Reboot().
In Reboot(), wait until the node comes up.

e2e: Fix GetCluster().

---

cmd/bootkube/render.go

Change bootstrap etcd service port to 20.

---

pkg/bootkube/bootstrap.go

If not overwriting, use the `O_EXCL` flag when opening the destination
file to ensure we create it.

pkg/bootkube: Fix time-of-check-to-time-of-use in copyFile

---

e2e/checkpointer_test.go

Add checkpointer tests for bootkube.
Tests are originally from [mantle/pluton](https://github.com/coreos/mantle/blob/master/pluton/tests/bootkube/checkpointertest.go).

e2e: Add checkpointer test

---

e2e/node.go

e2e: improve error reporting in Reboot()

---

hack/terraform-quickstart/main.tf
hack/terraform-quickstart/run-conformance.sh
hack/terraform-quickstart/start-cluster.sh
hack/terraform-quickstart/variables.tf
hack/tests/conformance-test.sh

add conformance script shim for terraform setup

---

cmd/bootkube/render.go
pkg/asset/asset.go
pkg/asset/tls.go

ref: https://github.com/kubernetes-incubator/bootkube/issues/582

selfHostedEtcd: autogen certs from CA cert

---

pkg/asset/asset.go
pkg/asset/k8s.go

Step 2 of https://github.com/kubernetes-incubator/bootkube/issues/582

SHE: autogen secrets containing etcd tls assets

---

cmd/bootkube/render.go
pkg/asset/internal/templates.go
pkg/asset/k8s.go
pkg/recovery/etcd_template.go
pkg/recovery/recover.go
pkg/util/etcdutil/migrate.go
pkg/util/etcdutil/util.go

Last step of https://github.com/kubernetes-incubator/bootkube/issues/582

selfHostedEtcd: enable TLS

---

.travis.yml
build/build-release.sh
pkg/asset/internal/templates.go
pkg/asset/tls.go

Just patching in #555 which is a good change but seems abandoned.

Use selected API server port in manifest templates

---

RELEASING.md

Add versioning notes to release docs

---

README.md
ROADMAP.md

Add roadmap doc

---

Documentation/alpha-features.md
pkg/asset/internal/templates.go

fix https://github.com/kubernetes-incubator/bootkube/issues/599

etcd_svc: tolerate unready endpoints

---

design-principles.md

Design principles doc

---

e2e/checkpointer_test.go
e2e/deleteapi_test.go
e2e/etcdscale_test.go
e2e/main_test.go
e2e/network_test.go
e2e/reboot_test.go
hack/multi-node/user-data.sample
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/single-node/user-data.sample
hack/tests/conformance-test.sh
pkg/asset/images.go

Should hopefully help stabilize etcd scale tests. cc @aaronlevy @abhinavdahiya @xiang90

etcd-operator: v0.4.2

---

e2e/checkpointer_test.go
e2e/etcdscale_test.go
e2e/main_test.go
e2e/node.go
e2e/reboot_test.go
e2e/smoke_test.go

Several improvements to e2e tests. Putting all in one PR to maximize probability of tests passing.

e2e improvements.

---

pkg/asset/images.go

kenc: bump to 0.0.2

---

e2e/README.md

e2e: remove requirements blurb

---

cmd/checkpoint/main.go

This is a requirement for kubelet authorization.
We still force the checkpointer to not check the kubelet's serving cert no matter what's in the kubeconfig, since in our deployments it's self signed.
Updates #648
Closes #625
cc @diegs

checkpointer: handle kubelet API denials and make kubeconfig configurable

---

pkg/asset/images.go

pod-checkpointer: bump to 0cd390e0bc1dcdcc714b20eda3435c3d00669d0e

---

RELEASING.md
pkg/asset/images.go

Update to use the latest checkpointer code by default

Updated default checkpointer image

---

pkg/asset/internal/templates.go

* Allow pods to communicate with themselves via service IP
* https://github.com/coreos/flannel/pull/849

Enable hairpinMode in flannel CNI config

---

.travis.yml

use the latest patch release of golang with 1.8 and 1.9

travis: use the latest patch release of golang

---

pkg/checkpoint/manifest.go

Somehow this snuck past the test--maybe I didn't actually trigger it
again.

checkpointer: chmod before close.

---

hack/multi-node/user-data.sample
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/single-node/user-data.sample
hack/tests/conformance-test.sh
pkg/asset/images.go

Starting the conformance tests as well.
Unblocks #742

hack,pkg: Update Kubernetes from v1.8.2 to v1.8.3

---

Documentation/development.md

Only Go version 1.8 is supported for building the project.

Make it clear that only Go version 1.8 is supported now

---

hack/multi-node/user-data.sample
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/single-node/user-data.sample
hack/tests/conformance-test.sh
pkg/asset/images.go

pkg,hack: Update Kubernetes from v1.8.3 to v1.8.4

---

pkg/asset/internal/templates.go

The pivot and checkpointer both appear to work fine without it.
If this works, possibly a partial fix for #495

Remove apiserver flock.

---

Documentation/development.md

Remove unnecessary quote in `development.md`.

Remove unnecessary quote

---

hack/multi-node/user-data.sample
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/single-node/user-data.sample
hack/tests/conformance-test.sh
pkg/asset/images.go

pkg,hack: Update Kubernetes from v1.8.4 to v1.8.5

---

Documentation/root-requirements.md

Documents the root user requirements of the bootkube components.

add root requirements doc

---

hack/multi-node/user-data.sample
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/single-node/user-data.sample
hack/tests/conformance-test.sh
pkg/asset/images.go

Running conformance and CNCF tests.

Update Kubernetes from v1.9.1 to v1.9.2

---

e2e/reboot_test.go

This is Eric's fix/changes from #831. Fixes #837.

wip: e2e: fix reboot test flakes

---

Documentation/disaster-recovery.md
pkg/recovery/recover.go

* Add some documentation on how bootkube recover works
* Remove self hosted etcd variables

add more bootkube recover docs

---

hack/quickstart/init-master.sh
hack/quickstart/init-node.sh

add a wait to make sure ssh is ready

---

pkg/asset/images.go

https://github.com/coreos/flannel/releases/tag/v0.10.0

pkg/asset: Update flannel to v0.10.0

---

hack/scripts/gatherlogs

small tweak to make sure the destination directory exists

logs: make sure destination dir exists

---

pkg/asset/internal/templates.go

manifests: remove deprecated --etcd-quorum-read flag

---

build/build-release.sh
hack/tests/conformance-gce.sh
hack/tests/conformance-test.sh

new round of security fixes in golang

bump to golang 1.9.4

---

Makefile
hack/multi-node/user-data.sample
hack/quickstart/kubelet.master
hack/quickstart/kubelet.worker
hack/single-node/user-data.sample
hack/tests/conformance-test.sh
pkg/asset/images.go

Update hyperkube image from v1.9.2 to v1.9.3

---

e2e/deleteapi_test.go

This waits for the real pods to be deleted instead of an apiserver
liveness check, since that is racy and doesn't convey much.
Part of follow-up work discussed in #824.

e2e: better delete api wait condition.

---

Documentation/development.md

Documentation: document new e2e command

---

e2e/checkpointer_test.go

updates https://github.com/kubernetes-incubator/bootkube/issues/851
There doesn't seem to be a good reason for this test to be rebooting nodes. Remove the reboots to see if it reduces flakey-ness.

e2e checkpointer test: remove node reboots

---

cmd/bootkube/recover.go

etcd can be secured with only a CA, and not require client certificates. This
fix relaxes the argument verification.
Fixes #903

recover: relax verification of etcd CAPath

---

pkg/bootkube/create.go

closes https://github.com/kubernetes-incubator/bootkube/issues/932

pkg/bootkube: fix create always printing an error

---

Documentation/disaster-recovery.md

docs: clarify 'latest' usage

---

cmd/bootkube/start.go
hack/jenkins/pipelines/bootkube-e2e/Jenkinsfile
hack/quickstart/init-master.sh
hack/terraform-quickstart/start-cluster.sh
pkg/bootkube/bootkube.go
pkg/bootkube/create.go

add strict mode for start

---

OWNERS

closes https://github.com/kubernetes-incubator/bootkube/issues/944
cc @colemickens @rithujohn191 @rphillips

OWNERS: update owners

---

hack/jenkins/README.md
hack/jenkins/images/hyperkube-builder/Dockerfile
hack/jenkins/jobs/hyperkube_release.groovy
hack/jenkins/pipelines/hyperkube-release/Jenkinsfile

* Builds and optionally pushes the built hyperkube image

add hyperkube release scripts

---

README.md

Catching up with kubernetes/community#1685.

README: Update the Slack link

---

Documentation/network-requirements.md
pkg/asset/internal/templates.go

Rebased https://github.com/kubernetes-incubator/bootkube/pull/719

Update flannel vxlan port to 4789

---

SECURITY_CONTACTS

Adds a security file
Fixes #987
/cc @aaronlevy @philips

add security file

---

pkg/asset/images.go

images: bump checkpointer for affinity fix

---

pkg/bootkube/create.go

The old mechanism used the namespace in the CRD which has no connection to the CustomResources the CRD wait loop is querying.
Second: the CRD wait logic used spec.Version which is now deprecated and defaulted to spec.Versions[0].Name. Hence, the URI was wrong as it lacked a version for manifests which depend on that defaulting.

start: fix CRD wait loop

---

Documentation/root-requirements.md

fix typo in line 6: Kubenetes -> Kubernetes

fix typo Kubenetes -> Kubernetes

---

pkg/checkpoint/runtime_service.go

Line 176&202: runtime sevice->runtime service

Typo in the returned message in runtime_service.go

---

pkg/recovery/recover.go

Delete repeated 'the'

---

README.md

Signed-off-by: Rui Cao <ruicao@alauda.io>

Fix typo: resouces -> resource

---

cmd/bootkube/render.go
cmd/checkpoint/README.md
e2e/internal/e2eutil/testworkload/nginx_workload.go

Fix typos:
commma -> comma, 
requried -> required, 
succesfully -> successfully, 
serivce -> service

Fix typos: commma  -> comma, requried -> required, etc

---

pkg/asset/images.go

* pod-checkpointer change https://github.com/kubernetes-incubator/bootkube/pull/1027

Update pod-checkpointer image to try secureClient first

---

Documentation/upgrading.md

Here are some small changes to the upgrading documentation that I found when doing following it myself. I took the liberty to do some small and simple improvements (like add the `set-image` example for kube-proxy).
I tried to split the logical changes in different commits and explain on each commit message, but if something is not clear please don't hesitate to ask.
Thanks a lot!
Rodrigo

Improve upgrading docs

---

pkg/asset/images.go

updates flannel

---

pkg/asset/images.go
pkg/asset/internal/templates.go

update coredns and config for 1.6.2

---

cmd/bootkube/render.go

Help text was not showing experimental calico

fixes help text to show experimental-calico

---

Documentation/alpha-features.md

* Fix broken link of api versioning documentation

Fix broken link of api versioning documentation

---

pkg/asset/asset.go
pkg/asset/internal/templates.go

Signed-off-by: Andrew Rynhard <andrew@andrewrynhard.com>

fix: create template methods on value receiver

---

pkg/bootkube/status.go

This ensures that the cache object is stopped.
Depends on #1085.

fix: stop pod watcher

---

pkg/recovery/etcd.go

This allows to decrypt etcd values if encryption at rest is enabled.
Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

feat: allow for transformation of raw etcd value in recovery backend

---

pkg/checkpoint/kubelet.go

Currently pod-checkpointer has hardcoded 127.0.0.1 as IP address of
kubelet API on the node. This means, it will be able to talk to the
kubelet only if the kubelet listens on 0.0.0.0 address, as kubelet must
be exposed to kube-apiserver.
In case where kubelet listens on some specific IP address, e.g. on
node's private IP, pod-checkpointer will no longer be able to talk to
it.
This PR allows setting kubelet IP via HOST_IP environment variable,
which can be set in the pod template using the following snippet:
```yaml
env:
- name: HOST_IP
valueFrom:
fieldRef:
fieldPath: status.hostIP
```
If the environment variable is not defined, it will fallback to use
127.0.0.1, to preserve backward compatibility.
Signed-off-by: Imran Pochi <imran@kinvolk.io>

pod-checkpointer: allow setting kubelet API address via HOST_IP env variable

---

Documentation/users-integrations.md
README.md

docs: Remove bare metal and add Lokomotive links
